# 01 Profile

#### this notebook is to run the profiling functions we created so we can diagnose any inconsistencies within our data

In [2]:
from src.profiler import run_profile

In [3]:
# execute the run_profile to generate the log files for all csv data
run_profile() # output of this is saved in /output/logs/

(                               file   start_s  ...  max_gap_s  gap_time_s
 0                          hv_power  0.011848  ...   6.268515  182.346495
 1                  imu_angular_rate  0.001332  ...   6.289916   28.896991
 2                  vehicle_position  2.188464  ...   6.215764   23.079007
 3                     vehicle_speed  2.188702  ...   6.215893   23.080508
 4             pedal_brakes_pressure  0.008073  ...   6.293122   35.408497
 5                       steer_angle  0.004815  ...   6.297040   39.091449
 6   vehicle_curvilinear_coordinates  2.188464  ...   6.215764   23.079007
 7                    pedal_throttle  0.008140  ...   6.292822   46.778663
 8                  imu_acceleration  0.002541  ...   6.290568   29.018449
 9            front_angular_velocity  0.000000  ...   6.292865   26.714684
 10        inv_r_id_a8_n_actual_filt  0.008493  ...   6.229199   23.719827
 11        inv_l_id_a8_n_actual_filt  0.008242  ...   6.230026   23.685588
 12            inv_r_id_27_iq_actual  0.004623  ...   6.230102   23.748749
 13            inv_l_id_27_iq_actual  0.004568  ...   6.228642   23.663537
 14                      GPS_NAV_PVT  1.914525  ...   6.263354   17.427218

 [15 rows x 11 columns],
                                file  ... longest_run_start_s
 0                          hv_power  ...         1922.060700
 1                  imu_angular_rate  ...          983.115400
 2                  imu_angular_rate  ...         1067.320481
 3                  imu_angular_rate  ...           57.353199
 4                  vehicle_position  ...         1873.054750
 5                  vehicle_position  ...         1897.333112
 6                  vehicle_position  ...           19.607176
 7                     vehicle_speed  ...         1976.254646
 8                     vehicle_speed  ...         1196.456935
 9             pedal_brakes_pressure  ...         1973.958972
 10            pedal_brakes_pressure  ...         1973.863384
 11                      steer_angle  ...         1979.257620
 12  vehicle_curvilinear_coordinates  ...         1970.532793
 13  vehicle_curvilinear_coordinates  ...         1899.151540
 14                   pedal_throttle  ...         1827.479473
 15                 imu_acceleration  ...         1951.559799
 16                 imu_acceleration  ...           22.506645
 17                 imu_acceleration  ...         1168.044625
 18                 imu_acceleration  ...            0.002541
 19           front_angular_velocity  ...         1982.367773
 20           front_angular_velocity  ...         1982.187107
 21        inv_r_id_a8_n_actual_filt  ...         1979.581827
 22        inv_l_id_a8_n_actual_filt  ...         2014.293104
 23            inv_r_id_27_iq_actual  ...         2124.136298
 24            inv_l_id_27_iq_actual  ...         2180.713425
 25                      GPS_NAV_PVT  ...            1.914525
 26                      GPS_NAV_PVT  ...            1.914525
 27                      GPS_NAV_PVT  ...            1.914525
 28                      GPS_NAV_PVT  ...            1.914525
 29                      GPS_NAV_PVT  ...            1.914525
 30                      GPS_NAV_PVT  ...         1940.747326
 31                      GPS_NAV_PVT  ...            6.740977
 32                      GPS_NAV_PVT  ...            1.914525
 33                      GPS_NAV_PVT  ...         1990.737171
 34                      GPS_NAV_PVT  ...            1.914525
 35                      GPS_NAV_PVT  ...            1.914525
 36                      GPS_NAV_PVT  ...         1922.413600
 37                      GPS_NAV_PVT  ...            1.914525
 38                      GPS_NAV_PVT  ...         2076.718211
 39                      GPS_NAV_PVT  ...         2120.888856
 40                      GPS_NAV_PVT  ...         2178.737920
 41                      GPS_NAV_PVT  ...         2205.308075
 42                      GPS_NAV_PVT  ...         2205.403970
 43                      GPS_NAV_PVT  ...         1898.748105
 44                      GPS_NAV_PVT  ...         2031.015486
 45                      GPS_NAV_PVT  ...           20.767301
 46                      GPS_NAV_PVT  ...           10.241307
 47                      GPS_NAV_PVT  ...         1057.333750
 48                      GPS_NAV_PVT  ...           39.528711
 49                      GPS_NAV_PVT  ...         1993.515668
 50                      GPS_NAV_PVT  ...          256.795141
 51                      GPS_NAV_PVT  ...         2085.219708
 52                      GPS_NAV_PVT  ...         2102.589022
 53                      GPS_NAV_PVT  ...            1.914525
 54                      GPS_NAV_PVT  ...            1.914525
 55                      GPS_NAV_PVT  ...         2182.510259

 [56 rows x 9 columns])

In [5]:
import pandas as pd
from src.config import OUT_LOGS

In [12]:
profile_file = pd.read_csv(OUT_LOGS / 'profile_files.csv')
profile_file

                               file   start_s  ...  max_gap_s  gap_time_s
0                          hv_power  0.011848  ...   6.268515  182.346495
1                  imu_angular_rate  0.001332  ...   6.289916   28.896991
2                  vehicle_position  2.188464  ...   6.215764   23.079007
3                     vehicle_speed  2.188702  ...   6.215893   23.080508
4             pedal_brakes_pressure  0.008073  ...   6.293122   35.408497
5                       steer_angle  0.004815  ...   6.297040   39.091449
6   vehicle_curvilinear_coordinates  2.188464  ...   6.215764   23.079007
7                    pedal_throttle  0.008140  ...   6.292822   46.778663
8                  imu_acceleration  0.002541  ...   6.290568   29.018449
9            front_angular_velocity  0.000000  ...   6.292865   26.714684
10        inv_r_id_a8_n_actual_filt  0.008493  ...   6.229199   23.719827
11        inv_l_id_a8_n_actual_filt  0.008242  ...   6.230026   23.685588
12            inv_r_id_27_iq_actual  0.004623  ...   6.230102   23.748749
13            inv_l_id_27_iq_actual  0.004568  ...   6.228642   23.663537
14                      GPS_NAV_PVT  1.914525  ...   6.263354   17.427218

[15 rows x 11 columns]

**Notes**
* notice some late starts (2s) in vehicle_position, vehicle_speed, vehicle_curvilinear_coordinates and GPS_NAV_PVT by approx. 2s
* the end_s is all the same.
* duration is ~2206 +/- 2s for the previously mentioned data
* n_samples reflects the different sample rate
* all data is sorted (which is good)
* there are no duplicated rows
* sampling rates are 20Hz,  ~100Hz, ~223Hz, and ~7Hz
* there are gaps in the data for the gap_factor = 3
* max gap duration is ~6s accross all data
* hv_power has a cumulative gap of ~182s / 2207 (~8% of data) compared to an avg of ~25-40s for the rest (1%-2% of data)
* the inverters and estimators ile all have ~70gaps and ~23s lost
* vehicle_position and vehicle_curvilinear_coordinates are identical (start, end, count, gaps)

In [9]:
profile_columns = pd.read_csv(OUT_LOGS / 'profile_columns.csv')
profile_columns

                               file  ... longest_run_start_s
0                          hv_power  ...         1922.060700
1                  imu_angular_rate  ...          983.115400
2                  imu_angular_rate  ...         1067.320481
3                  imu_angular_rate  ...           57.353199
4                  vehicle_position  ...         1873.054750
5                  vehicle_position  ...         1897.333112
6                  vehicle_position  ...           19.607176
7                     vehicle_speed  ...         1976.254646
8                     vehicle_speed  ...         1196.456935
9             pedal_brakes_pressure  ...         1973.958972
10            pedal_brakes_pressure  ...         1973.863384
11                      steer_angle  ...         1979.257620
12  vehicle_curvilinear_coordinates  ...         1970.532793
13  vehicle_curvilinear_coordinates  ...         1899.151540
14                   pedal_throttle  ...         1827.479473
15                 imu_acceleration  ...         1951.559799
16                 imu_acceleration  ...           22.506645
17                 imu_acceleration  ...         1168.044625
18                 imu_acceleration  ...            0.002541
19           front_angular_velocity  ...         1982.367773
20           front_angular_velocity  ...         1982.187107
21        inv_r_id_a8_n_actual_filt  ...         1979.581827
22        inv_l_id_a8_n_actual_filt  ...         2014.293104
23            inv_r_id_27_iq_actual  ...         2124.136298
24            inv_l_id_27_iq_actual  ...         2180.713425
25                      GPS_NAV_PVT  ...            1.914525
26                      GPS_NAV_PVT  ...            1.914525
27                      GPS_NAV_PVT  ...            1.914525
28                      GPS_NAV_PVT  ...            1.914525
29                      GPS_NAV_PVT  ...            1.914525
30                      GPS_NAV_PVT  ...         1940.747326
31                      GPS_NAV_PVT  ...            6.740977
32                      GPS_NAV_PVT  ...            1.914525
33                      GPS_NAV_PVT  ...         1990.737171
34                      GPS_NAV_PVT  ...            1.914525
35                      GPS_NAV_PVT  ...            1.914525
36                      GPS_NAV_PVT  ...         1922.413600
37                      GPS_NAV_PVT  ...            1.914525
38                      GPS_NAV_PVT  ...         2076.718211
39                      GPS_NAV_PVT  ...         2120.888856
40                      GPS_NAV_PVT  ...         2178.737920
41                      GPS_NAV_PVT  ...         2205.308075
42                      GPS_NAV_PVT  ...         2205.403970
43                      GPS_NAV_PVT  ...         1898.748105
44                      GPS_NAV_PVT  ...         2031.015486
45                      GPS_NAV_PVT  ...           20.767301
46                      GPS_NAV_PVT  ...           10.241307
47                      GPS_NAV_PVT  ...         1057.333750
48                      GPS_NAV_PVT  ...           39.528711
49                      GPS_NAV_PVT  ...         1993.515668
50                      GPS_NAV_PVT  ...          256.795141
51                      GPS_NAV_PVT  ...         2085.219708
52                      GPS_NAV_PVT  ...         2102.589022
53                      GPS_NAV_PVT  ...            1.914525
54                      GPS_NAV_PVT  ...            1.914525
55                      GPS_NAV_PVT  ...         2182.510259

[56 rows x 9 columns]

**Notes**
* no NaN values
* some columns are redundent as they have only one data such as imu_temperature (value = 0), headVeh, magDec, and others.
* behicle speed u had a longest run of 230s starting at s 1976 so it probably is when the car came to a stop at the end.
* front and read brake pressure, steer angle, and s also had a very long run starting at 1973s so also probably the car is parked at the end of the race.
* throttle freezes aarlier than the rest: constant run start at 1827s which is abt 150s before the car stops at 1976s, so either coasting or being pushed or the sensor froze (plot against speed to find out)
* position estimate (s) keeps changing while parked, it's the same for 144s from 1970 then changes again around 2115s with u = 0
* min wheel speed is negative (min = -0.54), inverter min is -1.4. offset or noise, need to check in standstill
* negative value for power means energy is flowing into the battery, min value of -0.56 either very little regen or noise -> check when it occurs to know if it is regen or just offset or noise

#### some findings from this notebook

1. constant columns that we can drop: imu_temperature, headVeh, magDec and the GPS date fields (year,month,day), valid,flags2,fixType (3 = 3D fix)
2. late starts for some estimators and GPS