In [1]:
from src.config import PIT_MIN_S, PROC_DATA
import pandas as pd
from src.preprocess import load_processed

In [2]:
df = load_processed()
df

,t_s,hv_power__power,imu_angular_rate__x,imu_angular_rate__y,imu_angular_rate__z,imu_acceleration__x,imu_acceleration__y,imu_acceleration__z,vehicle_position__x,vehicle_position__y,...,pedal_brakes_pressure__front,pedal_brakes_pressure__rear,pedal_throttle__throttle,steer_angle__angle,front_angular_velocity__fl,front_angular_velocity__fr,inv_r_id_a8_n_actual_filt__n_act_filt,inv_l_id_a8_n_actual_filt__n_act_filt,inv_r_id_27_iq_actual__iq_act_filt,inv_l_id_27_iq_actual__iq_act_filt
0,2.188702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.192702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
2,2.196702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
3,2.200702,0.131650,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
4,2.204702,0.121386,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.109383,0.051784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551187,2206.936702,-0.001526,-0.190444,-0.052721,-0.000712,0.002248,-0.020000,-0.983122,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,0.031180,0.000000
551188,2206.940702,-0.001526,-0.146536,-0.043939,-0.070965,0.002248,-0.012936,-0.968809,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.029027,0.000000
551189,2206.944702,-0.001526,-0.082120,-0.236204,-0.053140,0.002248,-0.016021,-0.953979,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551190,2206.948702,-0.001526,-0.142615,-0.047344,-0.044080,0.007444,-0.020000,-0.970781,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551191,2206.952702,-0.001526,-0.004415,-0.041300,-0.001003,0.012248,-0.015721,-0.981442,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000

In [25]:
df.columns

Index(['t_s', 'hv_power__power', 'imu_angular_rate__x', 'imu_angular_rate__y',
       'imu_angular_rate__z', 'imu_acceleration__x', 'imu_acceleration__y',
       'imu_acceleration__z', 'vehicle_position__x', 'vehicle_position__y',
       'vehicle_position__heading', 'vehicle_speed__u', 'vehicle_speed__v',
       'vehicle_curvilinear_coordinates__s',
       'vehicle_curvilinear_coordinates__n', 'pedal_brakes_pressure__front',
       'pedal_brakes_pressure__rear', 'pedal_throttle__throttle',
       'steer_angle__angle', 'front_angular_velocity__fl',
       'front_angular_velocity__fr', 'inv_r_id_a8_n_actual_filt__n_act_filt',
       'inv_l_id_a8_n_actual_filt__n_act_filt',
       'inv_r_id_27_iq_actual__iq_act_filt',
       'inv_l_id_27_iq_actual__iq_act_filt'],
      dtype='str')

In [8]:
df["vehicle_curvilinear_coordinates__s"]

0         790.998673
1         790.998673
2         790.998673
3         790.998673
4         790.998673
             ...
551187    736.999598
551188    736.999598
551189    736.999598
551190    736.999598
551191    736.999598
Name: vehicle_curvilinear_coordinates__s, Length: 551192, dtype: float64

In [10]:
from src.utils import find_standstills
standstills = find_standstills()

In [11]:
standstills

       start_s        end_s  duration_s
0     0.000000    13.002358   13.002358
1    20.790024    54.929918   34.139894
2   161.421000   176.054854   14.633854
3   192.778036   206.897613   14.119577
4   227.119072   242.465951   15.346879
5   977.176868  1157.391011  180.214143
6  1163.760712  1196.196530   32.435818
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [19]:
pit_cand = standstills[standstills["duration_s"] >= PIT_MIN_S]
pit_cand

       start_s        end_s  duration_s
5   977.176868  1157.391011  180.214143
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [14]:
from src.utils import find_laps
raw_laps = find_laps()

In [15]:
raw_laps

,lap_number,start_s,end_s,lap_time_s,has_stop,has_gap,has_pit,is_out_lap,valid
0,1,61.447598,133.758730,72.311132,False,False,False,False,True
1,2,133.758730,281.465908,147.707178,True,False,False,False,False
2,3,281.465908,348.448507,66.982599,False,False,False,False,True
3,4,348.448507,413.994435,65.545928,False,False,False,False,True
4,5,413.994435,477.396409,63.401974,False,False,False,False,True
5,6,477.396409,539.871968,62.475559,False,False,False,False,True
6,7,539.871968,603.920050,64.048082,False,True,False,False,False
7,8,603.920050,665.375170,61.455120,False,False,False,False,True
8,9,665.375170,726.564443,61.189273,False,True,False,False,False
9,10,726.564443,787.367604,60.803161,False,True,False,False,False
10,11,787.367604,848.838904,61.471300,False,True,False,False,False
11,12,848.838904,910.240131,61.401227,False,False,False,False,True
12,13,910.240131,972.009224,61.769093,False,False,False,False,True
13,14,972.009224,1203.733071,231.723847,True,True,True,True,False
14,15,1203.733071,1270.906110,67.173039,False,False,False,False,True
15,16,1270.906110,1334.621896,63.715786,False,True,False,False,False
16,17,1334.621896,1397.577341,62.955445,False,False,False,False,True
17,18,1397.577341,1459.020535,61.443194,False,False,False,False,True
18,19,1459.020535,1520.200158,61.179623,False,False,False,False,True
19,20,1520.200158,1587.460414,67.260256,False,False,False,False,True
20,21,1587.460414,1649.263642,61.803228,False,True,False,False,False
21,22,1649.263642,1712.916918,63.653276,False,False,False,False,True
22,23,1712.916918,1775.022498,62.105580,False,False,False,False,True

In [18]:
race_start_t = raw_laps["start_s"].iloc[0]
race_end_t = raw_laps["end_s"].iloc[-1]

In [21]:
pits = pit_cand[(pit_cand["start_s"] > race_start_t) & (pit_cand["end_s"] < race_end_t)]

In [22]:
pits

      start_s        end_s  duration_s
5  977.176868  1157.391011  180.214143

In [23]:
for i in range(len(pits)):
    stint_i = i +1
    stints = {
        stint_i : [pits["start_s"].iloc[i], pits["end_s"].iloc[i]]
    }

In [24]:
stints

{1: [np.float64(977.176868), np.float64(1157.391011)]}

In [1]:
from src.segment import find_segment_standstills

In [2]:
std = find_segment_standstills()
std

       start_s        end_s  duration_s
0     2.216702    13.008702      10.792
1    20.776702    54.928702      34.152
2   161.416702   176.068702      14.652
3   192.732702   206.908702      14.176
4   227.108702   242.484702      15.376
5   977.172702  1157.396702     180.224
6  1163.760702  1196.200702      32.440
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [5]:
pits_cand = std[std["duration_s"] >= PIT_MIN_S]
pits_cand

       start_s        end_s  duration_s
5   977.172702  1157.396702     180.224
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [18]:
df = load_processed()

In [27]:
data = df[(~df["front_angular_velocity__fl"].isna()) & (~df["front_angular_velocity__fr"].isna())]

In [29]:
data["front_angular_velocity__fr"]

7        -0.003052
8        -0.003052
9        -0.003052
10       -0.003052
11       -0.003052
            ...
551187   -0.003052
551188   -0.003052
551189   -0.003052
551190   -0.003052
551191   -0.003052
Name: front_angular_velocity__fr, Length: 544294, dtype: float64

In [1]:
from src.preprocess import load_processed
from src.loader import load_centerline
from src.segment import classify_standstills, define_stints, segment_laps
from src.utils import find_laps

In [2]:
df = load_processed()
track_length = load_centerline().attrs["length"]

In [3]:
standstills = classify_standstills(df)

In [4]:
df, stints = define_stints(df, track_length)

In [5]:
df, laps, gaps = segment_laps(df, standstills, track_length)

In [6]:
standstills

       start_s        end_s  duration_s  type
0     2.216702    13.008702      10.792  stop
1    20.776702    54.928702      34.152  stop
2   161.416702   176.068702      14.652  stop
3   192.732702   206.908702      14.176  stop
4   227.108702   242.484702      15.376  stop
5   977.172702  1157.396702     180.224   pit
6  1163.760702  1196.200702      32.440  stop
7  1829.972702  1908.044702      78.072   pit
8  1920.548702  2206.952702     286.404   pit

In [7]:
laps

    lap  stint      t_start        t_end  lap_time  has_pit  has_stop  has_gap
0     1      1    61.448702   133.748702    72.300    False     False     True
1     2      1   133.752702   281.456702   147.704    False      True     True
2     3      1   281.460702   348.440702    66.980    False     False     True
3     4      1   348.444702   413.988702    65.544    False     False     True
4     5      1   413.992702   477.384702    63.392    False     False     True
5     6      1   477.388702   539.864702    62.476    False     False     True
6     7      1   539.868702   603.916702    64.048    False     False     True
7     8      1   603.920702   665.368702    61.448    False     False     True
8     9      1   665.372702   726.560702    61.188    False     False     True
9    10      1   726.564702   787.360702    60.796    False     False     True
10   11      1   787.364702   848.828702    61.464    False     False     True
11   12      1   848.832702   910.232702    61.400    False     False     True
12   13      1   910.236702   972.000702    61.764    False     False     True
13   14      1   972.004702  1203.728702   231.724     True      True     True
14   15      2  1203.732702  1270.900702    67.168    False     False     True
15   16      2  1270.904702  1334.612702    63.708    False     False     True
16   17      2  1334.616702  1397.572702    62.956    False     False    False
17   18      2  1397.576702  1459.008702    61.432    False     False     True
18   19      2  1459.012702  1520.192702    61.180    False     False     True
19   20      2  1520.196702  1587.452702    67.256    False     False     True
20   21      2  1587.456702  1649.256702    61.800    False     False     True
21   22      2  1649.260702  1712.912702    63.652    False     False     True
22   23      2  1712.916702  1775.016702    62.100    False     False     True

In [8]:
gaps

    lap      t_start        t_end  duration_s     s_start       s_end
0     1   125.692702   125.988702       0.296  737.453005  737.770052
1     2   200.528702   200.572702       0.044  367.187395  367.186090
2     3   304.284702   304.404702       0.120  307.455988  307.750789
3     3   340.380702   340.456702       0.076  731.804109  732.068306
4     4   371.228702   371.676702       0.448  314.291650  314.684471
5     4   376.220702   376.500702       0.280  378.396287  379.034396
6     4   407.488702   407.992702       0.504  749.095514  749.665542
7     5   439.184702   439.500702       0.316  364.115051  364.519274
8     6   504.192702   504.240702       0.048  386.131779  386.309847
9     7   596.276702   597.600702       1.324  737.607516  738.481427
10    8   616.348702   616.424702       0.076  176.376896  176.661068
11    8   652.448702   652.524702       0.076  670.498173  670.747850
12    9   688.540702   688.624702       0.084  350.278746  350.595905
13    9   689.656702   691.684702       2.028  369.740145  371.149244
14    9   714.656702   714.700702       0.044  692.172323  692.473912
15    9   719.656702   719.768702       0.112  742.336665  742.577082
16   10   749.664702   749.760702       0.096  361.048840  361.318852
17   10   754.656702   756.824702       2.168  419.713178  420.390584
18   10   759.660702   759.688702       0.028  482.025529  482.221249
19   10   764.660702   764.692702       0.032  546.443222  546.642252
20   10   779.664702   779.708702       0.044  734.037465  734.204612
21   11   789.656702   789.684702       0.028   32.419537   32.650060
22   11   809.664702   810.928702       1.264  339.577757  340.682546
23   11   814.664702   815.180702       0.516  400.981866  401.522834
24   11   824.752702   824.916702       0.164  528.129443  528.412484
25   12   854.656702   854.688702       0.032   95.855842   96.129679
26   12   896.676702   896.860702       0.184  663.565938  663.858078
27   12   904.660702   904.724702       0.064  756.042893  756.242699
28   13   932.768702   932.972702       0.204  336.602259  337.172448
29   13   944.664702   944.712702       0.048  489.425168  489.626273
30   13   959.664702   959.716702       0.052  692.559496  692.875990
31   13   968.864702   968.944702       0.080  780.226786  780.395555
32   14   994.920702   995.124702       0.204  800.538839  800.538638
33   14   999.924702  1000.160702       0.236  800.491654  800.493839
34   14  1039.928702  1039.960702       0.032  800.229025  800.229025
35   14  1044.928702  1044.956702       0.028  800.194572  800.194572
36   14  1059.920702  1059.952702       0.032  800.270543  800.270527
37   14  1064.928702  1064.960702       0.032  799.351121  799.347091
38   14  1071.532702  1072.184702       0.652  798.714289  798.712009
39   14  1144.472702  1144.552702       0.080  798.999921  798.999921
40   14  1149.928702  1150.476702       0.548  798.999921  798.999921
41   14  1174.920702  1174.956702       0.036  791.488256  791.489083
42   15  1219.920702  1219.988702       0.068  196.958112  197.435891
43   15  1249.180702  1249.396702       0.216  588.614490  589.047039
44   15  1249.928702  1249.992702       0.064  599.345555  599.546190
45   15  1269.920702  1269.988702       0.068  795.208347  795.386196
46   16  1306.144702  1306.888702       0.744  487.577976  488.102370
47   18  1425.068702  1425.160702       0.092  399.107358  399.321015
48   19  1461.152702  1461.260702       0.108   32.262678   32.486919
49   19  1492.120702  1492.204702       0.084  483.751191  483.999942
50   20  1528.484702  1528.564702       0.080  122.641639  122.774092
51   21  1616.356702  1616.620702       0.264  428.659605  429.083990
52   21  1621.360702  1627.572702       6.212  494.240890  494.578953
53   22  1704.604702  1704.692702       0.088  729.044474  729.180763
54   23  1740.448702  1740.536702       0.088  404.372066  404.602450

In [9]:
# check: lap boundaries around the pit (flicker at ~973 s should not be a boundary)
laps[(laps["t_end"] > 900) & (laps["t_start"] < 1300)]

    lap  stint      t_start        t_end  lap_time  has_pit  has_stop  has_gap
11   12      1   848.832702   910.232702    61.400    False     False     True
12   13      1   910.236702   972.000702    61.764    False     False     True
13   14      1   972.004702  1203.728702   231.724     True      True     True
14   15      2  1203.732702  1270.900702    67.168    False     False     True
15   16      2  1270.904702  1334.612702    63.708    False     False     True

In [10]:
# lap times vs section 1 (raw data)
old = find_laps()
cmp = laps[["lap", "lap_time"]].merge(old[["lap_number", "lap_time_s"]],
                                      left_on="lap", right_on="lap_number")
cmp["diff_s"] = cmp["lap_time"] - cmp["lap_time_s"]
cmp

    lap  lap_time  lap_number  lap_time_s    diff_s
0     1    72.300           1   72.311132 -0.011132
1     2   147.704           2  147.707178 -0.003178
2     3    66.980           3   66.982599 -0.002599
3     4    65.544           4   65.545928 -0.001928
4     5    63.392           5   63.401974 -0.009974
5     6    62.476           6   62.475559  0.000441
6     7    64.048           7   64.048082 -0.000082
7     8    61.448           8   61.455120 -0.007120
8     9    61.188           9   61.189273 -0.001273
9    10    60.796          10   60.803161 -0.007161
10   11    61.464          11   61.471300 -0.007300
11   12    61.400          12   61.401227 -0.001227
12   13    61.764          13   61.769093 -0.005093
13   14   231.724          14  231.723847  0.000153
14   15    67.168          15   67.173039 -0.005039
15   16    63.708          16   63.715786 -0.007786
16   17    62.956          17   62.955445  0.000555
17   18    61.432          18   61.443194 -0.011194
18   19    61.180          19   61.179623  0.000377
19   20    67.256          20   67.260256 -0.004256
20   21    61.800          21   61.803228 -0.003228
21   22    63.652          22   63.653276 -0.001276
22   23    62.100          23   62.105580 -0.005580

In [11]:
old

,lap_number,start_s,end_s,lap_time_s,has_stop,has_gap,has_pit,is_out_lap,valid
0,1,61.447598,133.758730,72.311132,False,False,False,False,True
1,2,133.758730,281.465908,147.707178,True,False,False,False,False
2,3,281.465908,348.448507,66.982599,False,False,False,False,True
3,4,348.448507,413.994435,65.545928,False,False,False,False,True
4,5,413.994435,477.396409,63.401974,False,False,False,False,True
5,6,477.396409,539.871968,62.475559,False,False,False,False,True
6,7,539.871968,603.920050,64.048082,False,True,False,False,False
7,8,603.920050,665.375170,61.455120,False,False,False,False,True
8,9,665.375170,726.564443,61.189273,False,True,False,False,False
9,10,726.564443,787.367604,60.803161,False,True,False,False,False
10,11,787.367604,848.838904,61.471300,False,True,False,False,False
11,12,848.838904,910.240131,61.401227,False,False,False,False,True
12,13,910.240131,972.009224,61.769093,False,False,False,False,True
13,14,972.009224,1203.733071,231.723847,True,True,True,True,False
14,15,1203.733071,1270.906110,67.173039,False,False,False,False,True
15,16,1270.906110,1334.621896,63.715786,False,True,False,False,False
16,17,1334.621896,1397.577341,62.955445,False,False,False,False,True
17,18,1397.577341,1459.020535,61.443194,False,False,False,False,True
18,19,1459.020535,1520.200158,61.179623,False,False,False,False,True
19,20,1520.200158,1587.460414,67.260256,False,False,False,False,True
20,21,1587.460414,1649.263642,61.803228,False,True,False,False,False
21,22,1649.263642,1712.916918,63.653276,False,False,False,False,True
22,23,1712.916918,1775.022498,62.105580,False,False,False,False,True

In [12]:
gaps[gaps["lap"] == 13]

    lap     t_start       t_end  duration_s     s_start       s_end
28   13  932.768702  932.972702       0.204  336.602259  337.172448
29   13  944.664702  944.712702       0.048  489.425168  489.626273
30   13  959.664702  959.716702       0.052  692.559496  692.875990
31   13  968.864702  968.944702       0.080  780.226786  780.395555

next steps, the grid

In [4]:
distance = df["vehicle_curvilinear_coordinates__s"]

In [14]:
distance

0         790.998673
1         790.998673
2         790.998673
3         790.998673
4         790.998673
             ...
551187    736.999598
551188    736.999598
551189    736.999598
551190    736.999598
551191    736.999598
Name: vehicle_curvilinear_coordinates__s, Length: 551192, dtype: float64

In [5]:
distance.describe()

count    545234.000000
mean        526.804916
std         248.758087
min           0.000841
25%         325.110918
50%         615.227876
75%         736.999598
max         805.051987
Name: vehicle_curvilinear_coordinates__s, dtype: float64

In [7]:
import numpy as np

In [11]:
np.isnan(distance).sum()

np.int64(5958)

The car sensors take a reading abt every 0.1-0.25m of track, depending on the speed. if the grid points are 1m apart, they skip readings in between, so details like the exact spot where braking starts get blurred.

s itself is only accurate to within roughly a meter, putting grid points 0.05m apart doesnt make the data more accurate. we will just interpolate make up values between real readings.

a sweet spot would be 0.3m, it's close to the rate of the readings and it doesnt claim more precision than 2 really has. so the details are kept without inventing any.

the lap where the driver boxed will be dropped since it's mostly standstill, the rows where the car has stopped (the ones we suggested to be blue flags) will be dropped as well since they do not contribute to our analysis goals.

In [1]:
from src.preprocess import load_processed
from src.loader import load_centerline
from src.segment import classify_standstills, define_stints, segment_laps
from src.utils import find_laps

In [2]:
df = load_processed()
track_length = load_centerline().attrs["length"]
standstills = classify_standstills(df)
df, stints = define_stints(df, track_length)
df, laps, gaps = segment_laps(df, standstills, track_length)

In [3]:
valid_laps = laps[~laps["has_pit"]]
valid_laps

,lap,stint,t_start,t_end,lap_time,has_pit,has_stop,has_nan_s
0,1,1,61.448702,133.748702,72.300,False,False,True
1,2,1,133.752702,281.456702,147.704,False,True,True
2,3,1,281.460702,348.440702,66.980,False,False,True
3,4,1,348.444702,413.988702,65.544,False,False,True
4,5,1,413.992702,477.384702,63.392,False,False,True
5,6,1,477.388702,539.864702,62.476,False,False,True
6,7,1,539.868702,603.916702,64.048,False,False,True
7,8,1,603.920702,665.368702,61.448,False,False,True
8,9,1,665.372702,726.560702,61.188,False,False,True
9,10,1,726.564702,787.360702,60.796,False,False,True
10,11,1,787.364702,848.828702,61.464,False,False,True
11,12,1,848.832702,910.232702,61.400,False,False,True
12,13,1,910.236702,972.000702,61.764,False,False,True
14,15,2,1203.732702,1270.900702,67.168,False,False,True
15,16,2,1270.904702,1334.612702,63.708,False,False,True
16,17,2,1334.616702,1397.572702,62.956,False,False,False
17,18,2,1397.576702,1459.008702,61.432,False,False,True
18,19,2,1459.012702,1520.192702,61.180,False,False,True
19,20,2,1520.196702,1587.452702,67.256,False,False,True
20,21,2,1587.456702,1649.256702,61.800,False,False,True
21,22,2,1649.260702,1712.912702,63.652,False,False,True
22,23,2,1712.916702,1775.016702,62.100,False,False,True

In [4]:
standstills

       start_s        end_s  duration_s  type
0     2.216702    13.008702      10.792  stop
1    20.776702    54.928702      34.152  stop
2   161.416702   176.068702      14.652  stop
3   192.732702   206.908702      14.176  stop
4   227.108702   242.484702      15.376  stop
5   977.172702  1157.396702     180.224   pit
6  1163.760702  1196.200702      32.440  stop
7  1829.972702  1908.044702      78.072   pit
8  1920.548702  2206.952702     286.404   pit

In [5]:
df

,t_s,hv_power__power,imu_angular_rate__x,imu_angular_rate__y,imu_angular_rate__z,imu_acceleration__x,imu_acceleration__y,imu_acceleration__z,vehicle_position__x,vehicle_position__y,...,pedal_throttle__throttle,steer_angle__angle,front_angular_velocity__fl,front_angular_velocity__fr,inv_r_id_a8_n_actual_filt__n_act_filt,inv_l_id_a8_n_actual_filt__n_act_filt,inv_r_id_27_iq_actual__iq_act_filt,inv_l_id_27_iq_actual__iq_act_filt,stint,lap
0,2.188702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1,2.192702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,1.0,NaN
2,2.196702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,1.0,NaN
3,2.200702,0.131650,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,1.0,NaN
4,2.204702,0.121386,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,0.0,0.0,0.109383,0.051784,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551187,2206.936702,-0.001526,-0.190444,-0.052721,-0.000712,0.002248,-0.020000,-0.983122,-272.358276,38.590065,...,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,0.031180,0.000000,NaN,NaN
551188,2206.940702,-0.001526,-0.146536,-0.043939,-0.070965,0.002248,-0.012936,-0.968809,-272.358276,38.590065,...,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.029027,0.000000,NaN,NaN
551189,2206.944702,-0.001526,-0.082120,-0.236204,-0.053140,0.002248,-0.016021,-0.953979,-272.358276,38.590065,...,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000,NaN,NaN
551190,2206.948702,-0.001526,-0.142615,-0.047344,-0.044080,0.007444,-0.020000,-0.970781,-272.358276,38.590065,...,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000,NaN,NaN
551191,2206.952702,-0.001526,-0.004415,-0.041300,-0.001003,0.012248,-0.015721,-0.981442,-272.358276,38.590065,...,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000,NaN,NaN

In [6]:
df.columns

Index(['t_s', 'hv_power__power', 'imu_angular_rate__x', 'imu_angular_rate__y',
       'imu_angular_rate__z', 'imu_acceleration__x', 'imu_acceleration__y',
       'imu_acceleration__z', 'vehicle_position__x', 'vehicle_position__y',
       'vehicle_position__heading', 'vehicle_speed__u', 'vehicle_speed__v',
       'vehicle_curvilinear_coordinates__s',
       'vehicle_curvilinear_coordinates__n', 'pedal_brakes_pressure__front',
       'pedal_brakes_pressure__rear', 'pedal_throttle__throttle',
       'steer_angle__angle', 'front_angular_velocity__fl',
       'front_angular_velocity__fr', 'inv_r_id_a8_n_actual_filt__n_act_filt',
       'inv_l_id_a8_n_actual_filt__n_act_filt',
       'inv_r_id_27_iq_actual__iq_act_filt',
       'inv_l_id_27_iq_actual__iq_act_filt', 'stint', 'lap'],
      dtype='str')

In [7]:
from src.segment import build_distance_grid

grid_df = build_distance_grid(df, laps, standstills, track_length, save=False)
grid_df.head()

,lap,stint,s,t_s,t_lap,pedal_throttle__throttle,pedal_brakes_pressure__front,pedal_brakes_pressure__rear,vehicle_speed__u,imu_acceleration__y,...,vehicle_position__x,vehicle_position__y,vehicle_curvilinear_coordinates__n,front_angular_velocity__fl,front_angular_velocity__fr,hv_power__power,inv_l_id_a8_n_actual_filt__n_act_filt,inv_r_id_a8_n_actual_filt__n_act_filt,inv_l_id_27_iq_actual__iq_act_filt,inv_r_id_27_iq_actual__iq_act_filt
0,1,1,0.0,61.448702,0.000000,0.0,0.202261,-0.003862,12.416146,-0.081361,...,-233.142593,59.599778,1.317841,64.650751,63.983078,6.426728,60.095477,59.551870,-0.220910,-0.299740
1,1,1,0.3,61.470096,0.021394,0.0,0.748472,-0.010277,12.361901,-0.071375,...,-233.203629,59.856278,1.308747,64.339636,63.853058,4.898252,59.962475,60.262657,0.168643,-0.174798
2,1,1,0.6,61.493532,0.044830,0.0,1.359158,0.073672,12.292153,-0.092184,...,-233.234146,60.137322,1.297246,64.025127,63.642816,3.223831,62.515649,60.991835,-0.004585,0.015845
3,1,1,0.9,61.516489,0.067787,0.0,1.615730,0.169559,12.258028,-0.091895,...,-233.264664,60.443164,1.291327,63.808614,63.419855,2.340842,62.523417,61.050407,-0.033194,-0.019285
4,1,1,1.2,61.537794,0.089092,0.0,1.509990,0.113274,12.233517,-0.051855,...,-233.296327,60.697909,1.284545,63.706500,63.237542,1.704026,61.062900,61.405074,-0.018387,-0.179600

In [8]:
# 1. same number of rows per lap, and no pit lap, number 14
grid_df.groupby("lap").size()

lap
1     2684
2     2684
3     2684
4     2684
5     2684
6     2684
7     2684
8     2684
9     2684
10    2684
11    2684
12    2684
13    2684
15    2684
16    2684
17    2684
18    2684
19    2684
20    2684
21    2684
22    2684
23    2684
dtype: int64

In [9]:
# 2. t_lap at the end of each lap ~ lap_time
last = grid_df.groupby("lap")["t_lap"].last()
cmp = laps.set_index("lap")[["lap_time"]].join(last, how="inner")
cmp["diff_s"] = cmp["t_lap"] - cmp["lap_time"]
cmp

     lap_time       t_lap    diff_s
lap
1      72.300   72.290684 -0.009316
2     147.704  147.694539 -0.009461
3      66.980   66.969199 -0.010801
4      65.544   65.534067 -0.009933
5      63.392   63.384953 -0.007047
6      62.476   62.466132 -0.009868
7      64.048   64.033258 -0.014742
8      61.448   61.441157 -0.006843
9      61.188   61.179748 -0.008252
10     60.796   60.785960 -0.010040
11     61.464   61.455027 -0.008973
12     61.400   61.390818 -0.009182
13     61.764   61.752442 -0.011558
15     67.168   67.156428 -0.011572
16     63.708   63.698641 -0.009359
17     62.956   62.944455 -0.011545
18     61.432   61.423446 -0.008554
19     61.180   61.172134 -0.007866
20     67.256   67.246115 -0.009885
21     61.800   61.789847 -0.010153
22     63.652   63.643354 -0.008646
23     62.100   62.091767 -0.008233

In [10]:
# 3. NaN share per channel (should be small, except hv_power )
grid_df.isna().mean().sort_values(ascending=False)

hv_power__power                          0.107811
pedal_throttle__throttle                 0.016783
pedal_brakes_pressure__rear              0.010923
pedal_brakes_pressure__front             0.010923
imu_acceleration__x                      0.004556
imu_acceleration__y                      0.004556
front_angular_velocity__fl               0.003709
front_angular_velocity__fr               0.003709
inv_r_id_27_iq_actual__iq_act_filt       0.001253
inv_l_id_a8_n_actual_filt__n_act_filt    0.001253
inv_l_id_27_iq_actual__iq_act_filt       0.001219
inv_r_id_a8_n_actual_filt__n_act_filt    0.001219
vehicle_speed__u                         0.000982
vehicle_position__y                      0.000965
vehicle_position__x                      0.000965
vehicle_curvilinear_coordinates__n       0.000965
t_lap                                    0.000000
lap                                      0.000000
t_s                                      0.000000
s                                        0.000000
stint                                    0.000000
dtype: float64

In [12]:
# 4. speed vs s for two laps
import plotly.express as px
two = grid_df[grid_df["lap"].isin([8, 20])]
px.line(two, x="s", y="vehicle_speed__u", color="lap")

## Finding corners

In [2]:
import plotly.graph_objects as go
from src.loader import load_centerline

cl = load_centerline()

fig = go.Figure()

# track, coloured by curvature (red/blue = opposite signs, white = straight)
fig.add_trace(go.Scatter(
    x=cl["x"], y=cl["y"],
    mode="markers",
    marker=dict(size=4, color=cl["curvature"], colorscale="RdBu", cmid=0,
                colorbar=dict(title="curvature")),
    customdata=cl[["s", "curvature"]],
    hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
    name="centerline",
))


# equal scales so the track shape isn't distorted
fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title="Centerline: direction of travel and curvature",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000)
fig.update_layout(legend=dict(orientation="h", y=-0.1))
fig.show()

we will define the apex as the max curvature in the track

testing best parameters to define a staright vs a corner

im just eyeballing this part, after looking at the plot above and inspecting certain regions, i think teh regions that i could consider to be "straight" have |curvature| < 0.02 and they last about 20min, shorter than that is part of a corner. but i could be wrong?

In [14]:
import numpy as np
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021      # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long

cl = load_centerline()

# 1. points with low curvature
low = (cl["curvature"].abs() < K_STRAIGHT).to_numpy()

# 2. number each run of consecutive equal values
run_id = np.concatenate([[0], np.cumsum(low[1:] != low[:-1])])

# 3. the track is a loop: if first and last points have the same value, they're the same run
if low[0] == low[-1] and run_id[-1] != 0:
    run_id[run_id == run_id[-1]] = 0

# 4. length of each run (1 point = 1 m) and keep only long-enough low-curvature runs
run_len = np.bincount(run_id)
cl["is_straight"] = low & (run_len[run_id] >= MIN_STRAIGHT_M)

fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"],
        mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

# equal scales so the track shape isn't distorted
fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Straights (|curvature| < {K_STRAIGHT} for ≥ {MIN_STRAIGHT_M} m) vs corners",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000,
                  legend=dict(orientation="h", y=-0.1))
fig.show()

In [22]:
import numpy as np
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021      # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long
K_CORNER = 0.038


cl = load_centerline()

# 1. points with low curvature
low = (cl["curvature"].abs() < K_STRAIGHT).to_numpy()

# 2. number each run of consecutive equal values
run_id = np.concatenate([[0], np.cumsum(low[1:] != low[:-1])])

# 3. the track is a loop: if first and last points have the same value, they're the same run
if low[0] == low[-1] and run_id[-1] != 0:
    run_id[run_id == run_id[-1]] = 0

# 4. length of each run (1 point = 1 m) and keep only long-enough low-curvature runs
run_len = np.bincount(run_id)
cl["is_straight"] = low & (run_len[run_id] >= MIN_STRAIGHT_M)

fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"],
        mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

# equal scales so the track shape isn't distorted
fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Straights (|curvature| < {K_STRAIGHT} for ≥ {MIN_STRAIGHT_M} m) vs corners",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000,
                  legend=dict(orientation="h", y=-0.1))
sharp = cl[cl["curvature"].abs() > K_CORNER]
fig.add_trace(go.Scatter(
    x=sharp["x"], y=sharp["y"],
    mode="markers",
    marker=dict(size=3, color="black", symbol="x"),
    hoverinfo="skip",
    showlegend=False,
))
fig.show()

it seems like there are some peaks where curvature goes from 0.02 to 0.07 in one m and goes back down (s = 263), let's smooth it out using a rolling average before we threshold.

In [ ]:
import numpy as np
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021     # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long
K_CORNER = 0.0385       # |curvature| above this = clearly a corner
SMOOTH_WINDOW_M = 5   # rolling-mean window (odd number, 1 point = 1 m)

def smooth_circular(values: np.ndarray, window: int):
    """Rolling mean over `window` points, wrapping around the end of the loop."""
    half = window // 2
    padded = np.concatenate([values[-half:], values, values[:half]])
    return np.convolve(padded, np.ones(window) / window, mode="valid")

cl = load_centerline()
cl["curvature_smooth"] = smooth_circular(cl["curvature"].to_numpy(), SMOOTH_WINDOW_M)

# straights: low smoothed curvature for at least MIN_STRAIGHT_M
low = (cl["curvature_smooth"].abs() < K_STRAIGHT).to_numpy()
run_id = np.concatenate([[0], np.cumsum(low[1:] != low[:-1])])
if low[0] == low[-1] and run_id[-1] != 0:          # loop: join first and last run
    run_id[run_id == run_id[-1]] = 0
run_len = np.bincount(run_id)
cl["is_straight"] = low & (run_len[run_id] >= MIN_STRAIGHT_M)

fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"],
        mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature_smooth"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

# sharp points on top
sharp = cl[cl["curvature_smooth"].abs() > K_CORNER]
fig.add_trace(go.Scatter(
    x=sharp["x"], y=sharp["y"],
    mode="markers",
    marker=dict(size=3, color="black", symbol="x"),
    hoverinfo="skip",
    showlegend=False,
))

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Straights vs corners (smoothed {SMOOTH_WINDOW_M} m, "
                        f"|curvature| < {K_STRAIGHT} for ≥ {MIN_STRAIGHT_M} m)",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000,
                  legend=dict(orientation="h", y=-0.1))
fig.show()

looks good.

let's add the apex, the apex is the point with the highest curvature in a corner.


going to also number the corners starting from the start line and the R/L indicates if it's a right-hander or left-hander respectively

In [ ]:
import numpy as np
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021     # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long
K_CORNER = 0.0385       # |curvature| above this = clearly a corner
SMOOTH_WINDOW_M = 5   # rolling-mean window (odd number, 1 point = 1 m)


cl = load_centerline()
cl["curvature_smooth"] = smooth_circular(cl["curvature"].to_numpy(), SMOOTH_WINDOW_M)

# straights: low smoothed curvature for at least MIN_STRAIGHT_M
low = (cl["curvature_smooth"].abs() < K_STRAIGHT).to_numpy()
run_id = np.concatenate([[0], np.cumsum(low[1:] != low[:-1])])
if low[0] == low[-1] and run_id[-1] != 0:          # loop: join first and last run
    run_id[run_id == run_id[-1]] = 0
run_len = np.bincount(run_id)
cl["is_straight"] = low & (run_len[run_id] >= MIN_STRAIGHT_M)

fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"],
        mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature_smooth"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

# sharp points on top
sharp = cl[cl["curvature_smooth"].abs() > K_CORNER]
# corners = runs of consecutive points with |smoothed curvature| > K_CORNER
high = (cl["curvature_smooth"].abs() > K_CORNER).to_numpy()
run_id = np.concatenate([[0], np.cumsum(high[1:] != high[:-1])])
if high[0] == high[-1] and run_id[-1] != 0:          # loop: join first and last run
    run_id[run_id == run_id[-1]] = 0

# apex = point of highest |curvature| inside each high run
cl["run"] = run_id
high_pts = cl[high]
apex_idx = high_pts.groupby("run")["curvature_smooth"].apply(lambda c: c.abs().idxmax())
apexes = cl.loc[apex_idx].sort_values("s").reset_index(drop=True)
apexes["corner"] = np.arange(1, len(apexes) + 1)
apexes["direction"] = np.where(apexes["curvature_smooth"] > 0, "L", "R")

fig.add_trace(go.Scatter(
    x=apexes["x"], y=apexes["y"],
    mode="markers+text",
    marker=dict(size=9, color="gold", line=dict(width=1, color="black")),
    text=apexes["corner"].astype(str) + apexes["direction"],
    textposition="top center",
    customdata=apexes[["s", "curvature_smooth"]],
    hovertemplate="apex s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
    name="apex",
))

print(f"{len(apexes)} corners")
apexes[["corner", "direction", "s", "curvature_smooth"]]
fig.add_trace(go.Scatter(
    x=sharp["x"], y=sharp["y"],
    mode="markers",
    marker=dict(size=3, color="black", symbol="x"),
    hoverinfo="skip",
    showlegend=False,
))

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Straights vs corners (smoothed {SMOOTH_WINDOW_M} m, "
                        f"|curvature| < {K_STRAIGHT} for ≥ {MIN_STRAIGHT_M} m)",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000,
                  legend=dict(orientation="h", y=-0.1))
fig.show()

30 corners

best i could do tbh

so we have about 30 apexes, an apex != corner, a corner can have more than one apex.

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021     # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long
K_CORNER = 0.0385      # |curvature| above this = clearly a corner
SMOOTH_WINDOW_M = 5    # rolling-mean window (odd number, 1 point = 1 m)



def runs_of(mask: np.ndarray) :
    """Number each run of consecutive equal values; first and last run joined (track is a loop)."""
    run_id = np.concatenate([[0], np.cumsum(mask[1:] != mask[:-1])])
    if mask[0] == mask[-1] and run_id[-1] != 0:
        run_id[run_id == run_id[-1]] = 0
    return run_id

cl = load_centerline()
cl["curvature_smooth"] = smooth_circular(cl["curvature"].to_numpy(), SMOOTH_WINDOW_M)
curv = cl["curvature_smooth"].abs().to_numpy()      # |curvature|, one value per metre

# straights: low curvature for at least MIN_STRAIGHT_M
low = curv < K_STRAIGHT
low_runs = runs_of(low)
cl["is_straight"] = low & (np.bincount(low_runs)[low_runs] >= MIN_STRAIGHT_M)

# apexes: one per run of high curvature, at its sharpest point
high = curv > K_CORNER
cl["high_run"] = runs_of(high)
apex_idx = cl[high].groupby("high_run")["curvature_smooth"].apply(lambda c: c.abs().idxmax())
apexes = cl.loc[apex_idx].sort_values("s").reset_index(drop=True)
apexes["corner"] = np.arange(1, len(apexes) + 1)
apexes["direction"] = np.where(apexes["curvature_smooth"] > 0, "L", "R")

# plot
fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"], mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature_smooth"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

sharp = cl[high]
fig.add_trace(go.Scatter(
    x=sharp["x"], y=sharp["y"], mode="markers",
    marker=dict(size=3, color="black", symbol="x"),
    hoverinfo="skip", showlegend=False,
))

fig.add_trace(go.Scatter(
    x=apexes["x"], y=apexes["y"], mode="markers+text",
    marker=dict(size=9, color="gold", line=dict(width=1, color="black")),
    text=apexes["corner"].astype(str) + apexes["direction"],
    textposition="top center",
    customdata=apexes[["s", "curvature_smooth"]],
    hovertemplate="apex s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
    name="apex",
))

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Corners (smoothed {SMOOTH_WINDOW_M} m, peak > {K_CORNER})",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000, legend=dict(orientation="h", y=-0.1))
fig.show()

In [80]:
pairs = []
for i in range(len(apexes) - 1):
    a, b = apexes.iloc[i], apexes.iloc[i + 1]
    if a["direction"] == b["direction"]:
        between = curv[int(a["s"]):int(b["s"]) + 1]
        pairs.append({"pair": f"{a['corner']}{a['direction']}-{b['corner']}{b['direction']}",
                      "distance_m": b["s"] - a["s"],
                      "min_curv_between": between.min()})
pd.DataFrame(pairs)

      pair  distance_m  min_curv_between
0    1L-2L        85.0          0.000226
1    6L-7L        37.0          0.025223
2   9L-10L        49.0          0.000296
3  14L-15L        15.0          0.036481
4  20R-21R        15.0          0.029862
5  21R-22R        17.0          0.035776
6  22R-23R        69.0          0.000276
7  26L-27L        67.0          0.000044
8  28R-29R        37.0          0.021357

looking at the graph and the table, i think two apexes belng to the same corner if these conditions apply:
1. they have the same direction
2. the min curvature between them is >= 0.03 
3. the distance between them is <= 35m

In [82]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from src.loader import load_centerline

K_STRAIGHT = 0.021     # |curvature| below this = straight-ish
MIN_STRAIGHT_M = 20    # straight-ish stretch must be at least this long
K_CORNER = 0.0385      # |curvature| above this = clearly a corner
SMOOTH_WINDOW_M = 5    # rolling-mean window (odd number, 1 point = 1 m)
K_LINK = 0.025         # curvature between two apexes must stay above this to be one corner
MAX_LINK_M = 35        # and the apexes must be at most this far apart



cl = load_centerline()
cl["curvature_smooth"] = smooth_circular(cl["curvature"].to_numpy(), SMOOTH_WINDOW_M)
curv = cl["curvature_smooth"].abs().to_numpy()      # |curvature|, one value per metre
n = len(curv)

# --- straights: low curvature for at least MIN_STRAIGHT_M ---
low = curv < K_STRAIGHT
low_runs = runs_of(low)
cl["is_straight"] = low & (np.bincount(low_runs)[low_runs] >= MIN_STRAIGHT_M)

# --- apexes: one per run of high curvature, at its sharpest point ---
high = curv > K_CORNER
cl["high_run"] = runs_of(high)
apex_idx = cl[high].groupby("high_run")["curvature_smooth"].apply(lambda c: c.abs().idxmax())
apexes = cl.loc[apex_idx].sort_values("s").reset_index(drop=True)
apexes["direction"] = np.where(apexes["curvature_smooth"] > 0, "L", "R")

# --- group apexes into corners ---
def same_corner(a, b) -> bool:
    """Apex b follows apex a: same direction, close enough, and the track keeps turning between them."""
    if a["direction"] != b["direction"]:
        return False
    i, j = int(a["s"]), int(b["s"])
    between = curv[i:j + 1] if j >= i else np.concatenate([curv[i:], curv[:j + 1]])  # wrap
    distance = (j - i) % n
    return distance <= MAX_LINK_M and between.min() >= K_LINK

corner_id = [0]
for k in range(1, len(apexes)):
    if same_corner(apexes.iloc[k - 1], apexes.iloc[k]):
        corner_id.append(corner_id[-1])
    else:
        corner_id.append(corner_id[-1] + 1)
corner_id = np.array(corner_id)

# loop: last apex and first apex may be the same corner across the start/finish line
if len(apexes) > 1 and same_corner(apexes.iloc[-1], apexes.iloc[0]):
    corner_id[corner_id == corner_id[-1]] = corner_id[0]

apexes["corner"] = pd.factorize(corner_id)[0] + 1      # renumber 1..N in order

# main apex of each corner = its sharpest apex
main_idx = apexes.groupby("corner")["curvature_smooth"].apply(lambda c: c.abs().idxmax())
apexes["is_main"] = apexes.index.isin(main_idx)

# --- plot ---
fig = go.Figure()
for is_straight, colour, name in [(True, "blue", "straight"), (False, "red", "corner")]:
    part = cl[cl["is_straight"] == is_straight]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"], mode="markers",
        marker=dict(size=4, color=colour),
        customdata=part[["s", "curvature_smooth"]],
        hovertemplate="s=%{customdata[0]:.0f} m<br>curvature=%{customdata[1]:.04f}<extra></extra>",
        name=name,
    ))

sharp = cl[high]
fig.add_trace(go.Scatter(
    x=sharp["x"], y=sharp["y"], mode="markers",
    marker=dict(size=3, color="black", symbol="x"),
    hoverinfo="skip", showlegend=False,
))

for is_main, size, colour, name in [(True, 11, "gold", "main apex"), (False, 7, "green", "other apex")]:
    part = apexes[apexes["is_main"] == is_main]
    fig.add_trace(go.Scatter(
        x=part["x"], y=part["y"],
        mode="markers+text" if is_main else "markers",
        marker=dict(size=size, color=colour, line=dict(width=1, color="black")),
        text=part["corner"].astype(str) + part["direction"],
        textposition="top center",
        customdata=part[["corner", "s", "curvature_smooth"]],
        hovertemplate="corner %{customdata[0]}<br>apex s=%{customdata[1]:.0f} m"
                      "<br>curvature=%{customdata[2]:.04f}<extra></extra>",
        name=name,
    ))

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title=f"Corners (smoothed {SMOOTH_WINDOW_M} m, peak > {K_CORNER}, "
                        f"linked if curvature ≥ {K_LINK} and ≤ {MAX_LINK_M} m apart)",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000, legend=dict(orientation="h", y=-0.1))
fig.show()

print(f"{apexes['corner'].nunique()} corners, {len(apexes)} apexes")

27 corners, 30 apexes

27 corners, 30 apexes

Test the new functions

In [5]:
import pandas as pd
from src.preprocess import load_processed
from src.loader import load_centerline
from src.segment import (classify_standstills, define_stints, segment_laps,
                         build_distance_grid, find_corners, build_zones, label_zones)

In [6]:
df = load_processed()
centerline = load_centerline()
track_length = centerline.attrs["length"]

In [7]:
standstills = classify_standstills(df)
df, stints = define_stints(df, track_length)
df, laps, gaps = segment_laps(df, standstills, track_length)

In [8]:
grid_df = build_distance_grid(df, laps, standstills, track_length, save=True) # set to false if you don't want to save the results

In [9]:
cl, apexes = find_corners(centerline)
cl, zones = build_zones(cl, apexes)

In [10]:
grid_df = label_zones(grid_df, cl, zones)

In [11]:
zones

    zone      type  corner  s_start  s_end direction  s_apex
0      1  straight     NaN    802.0   18.0       NaN     NaN
1      2    corner     1.0     19.0   66.0         L    25.0
2      3  straight     NaN     67.0  104.0       NaN     NaN
3      4    corner     2.0    105.0  116.0         L   110.0
4      5    corner     3.0    117.0  127.0         R   122.0
5      6    corner     4.0    128.0  138.0         L   132.0
6      7    corner     5.0    139.0  179.0         R   142.0
7      8    corner     6.0    180.0  202.0         L   189.0
8      9    corner     7.0    203.0  263.0         L   226.0
9     10  straight     NaN    264.0  302.0       NaN     NaN
10    11    corner     8.0    303.0  318.0         R   313.0
11    12    corner     9.0    319.0  329.0         L   323.0
12    13    corner    10.0    330.0  380.0         L   372.0
13    14    corner    11.0    381.0  389.0         R   385.0
14    15    corner    12.0    390.0  400.0         L   395.0
15    16    corner    13.0    401.0  409.0         R   405.0
16    17    corner    14.0    410.0  448.0         L   432.0
17    18    corner    15.0    449.0  464.0         R   455.0
18    19    corner    16.0    465.0  481.0         L   476.0
19    20    corner    17.0    482.0  495.0         R   491.0
20    21    corner    18.0    496.0  510.0         L   500.0
21    22    corner    19.0    511.0  563.0         R   530.0
22    23  straight     NaN    564.0  591.0       NaN     NaN
23    24    corner    20.0    592.0  624.0         R   616.0
24    25    corner    21.0    625.0  635.0         L   629.0
25    26    corner    22.0    636.0  645.0         R   640.0
26    27    corner    23.0    646.0  669.0         L   652.0
27    28  straight     NaN    670.0  705.0       NaN     NaN
28    29    corner    24.0    706.0  725.0         L   719.0
29    30    corner    25.0    726.0  745.0         R   732.0
30    31    corner    26.0    746.0  777.0         R   769.0
31    32    corner    27.0    778.0  801.0         L   789.0

There are no kinks here

Let's visualize them, we will use black for straights and use alternating colors for corners

In [12]:
import numpy as np
import plotly.graph_objects as go

# colour per centerline metre: straights black, kinks grey, corners alternating by corner number
plot = cl.merge(zones[["zone", "type", "corner"]], on="zone", how="left")
corner_colours = ["#e4572e", "#2e86ab"]          # orange-red / blue
plot["colour"] = np.select(
    [plot["type"] == "straight", plot["type"] == "kink"],
    ["black", "grey"],
    default=[corner_colours[int(c) % 2] if pd.notna(c) else "black" for c in plot["corner"]],
)

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=plot["x"], y=plot["y"], mode="markers",
    marker=dict(size=5, color=plot["colour"]),
    customdata=plot[["s", "zone", "type", "corner"]],
    hovertemplate="s=%{customdata[0]:.0f} m<br>zone %{customdata[1]} (%{customdata[2]})"
                  "<br>corner %{customdata[3]}<extra></extra>",
    showlegend=False,
))

# corner numbers at each main apex
main = apexes[apexes["is_main"]]
fig.add_trace(go.Scatter(
    x=main["x"], y=main["y"], mode="text",
    text=main["corner"].astype(str) + main["direction"],
    textposition="top center", hoverinfo="skip", showlegend=False,
))

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_layout(title="Zones: straights (black), corners (alternating colours)",
                  xaxis_title="x (m, east)", yaxis_title="y (m, north)",
                  height=700, width=1000)
fig.show()

6L and 7L could be considered one double apex corner but because it is so long, it did not fall within our chosen metrics for defining a corner, but we will note that when doing the analysis

## Grid phases
next, will label each grid point.

to start off, we can observe the behavior of the two drivers across the two stints in terms of throttle, braking, and steering.
the goal is to observe the throttle pedal behavior of teh derivers and define what "full throttle" looks like for both drivers, along with how the steering looks like along the straights. we also want to see how the braking pressure is applied in corners.

In [13]:
grid = grid_df

In [14]:
grid.columns

Index(['lap', 'stint', 's', 't_s', 't_lap', 'pedal_throttle__throttle',
       'pedal_brakes_pressure__front', 'pedal_brakes_pressure__rear',
       'vehicle_speed__u', 'imu_acceleration__y', 'imu_acceleration__x',
       'vehicle_position__x', 'vehicle_position__y',
       'vehicle_curvilinear_coordinates__n', 'front_angular_velocity__fl',
       'front_angular_velocity__fr', 'hv_power__power',
       'inv_l_id_a8_n_actual_filt__n_act_filt',
       'inv_r_id_a8_n_actual_filt__n_act_filt',
       'inv_l_id_27_iq_actual__iq_act_filt',
       'inv_r_id_27_iq_actual__iq_act_filt', 'steer_angle__angle', 'zone',
       'type', 'corner'],
      dtype='str')

In [15]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from src.loader import load_centerline
from src.segment import find_corners, build_zones, label_zones
from src.config import PROC_DATA

THROTTLE = "pedal_throttle__throttle"
BRAKE = "pedal_brakes_pressure__front"
STEER = "steer_angle__angle"

grid = pd.read_parquet(PROC_DATA /"laps_distance.parquet")

cl = load_centerline()
cl, apexes = find_corners(cl)
cl, zones = build_zones(cl, apexes)
grid = label_zones(grid, cl, zones)
if "type" not in grid.columns:
    grid = grid.merge(zones[["zone", "type"]], on="zone", how="left")

# steering on straights only, as an absolute value
straights = grid[grid["type"] == "straight"].copy()
straights["abs_steer"] = straights[STEER].abs()

STINT_COLORS = {1: "#1f77b4", 2: "#ff7f0e"}


def overlay_hist(data, col, bin_width, title, xlabel, log_y=False):
    """One figure: one histogram per stint, overlaid, as % of that stint's points."""
    values = data[col].dropna()
    fig = go.Figure()
    for stint, g in data.groupby("stint"):
        fig.add_trace(
            go.Histogram(
                x=g[col].dropna(),
                xbins=dict(start=values.min(), end=values.max() + bin_width,
                           size=bin_width),
                histnorm="percent",
                opacity=0.5,
                name=f"stint {stint}",
                marker_color=STINT_COLORS.get(stint),
            )
        )
    fig.update_layout(
        title=title,
        xaxis_title=xlabel,
        yaxis_title="% of grid points in the stint",
        barmode="overlay",
        height=650,
        width=1600,
        font=dict(size=15),
    )
    if log_y:
        fig.update_yaxes(type="log")
    fig.show()


overlay_hist(grid, THROTTLE, bin_width=0.01,
             title="Throttle, whole lap", xlabel="throttle (0–1)", log_y=True)

overlay_hist(grid, BRAKE, bin_width=0.25,
             title="Front brake pressure, whole lap", xlabel="pressure (bar)", log_y=True)

overlay_hist(straights, "abs_steer", bin_width=0.25,
             title="|Steering|, straights only", xlabel="|steering angle| (deg)")

In teh straights:
* steering angle in the first stint seems to hover around ~1-1.5 degrees whereas in the second stint it seems to be more around ~3.5-4.5 degrees.
    - the 4 degrees in stint 2 could be an offset but it could also be the driver wiggling from -4 to +4 to -4 to +4 (sawing). they both give a peak at 4. if we plot the sign we can actually know which one it is. 

on whole lap:
1. throttle's highest value is 95% on stint 1 but in stint 2 it reaches a max value of 84%, and the trend overall in the second stint seems to be more cautious and less agressive than the 1st stint. but the 95% is only for 0.03% of the lap so either driver really reaches "full throttle". moreover, the throttle being off corresponds to teh value of 0. there doesnt seem to be  natural cutoff for steady throttle.
2. driver in stint 1 seems to apply more braking pressure than the second driver in stint 2. brake being off ~0-0.25bar with a trend going until ~0.5-1, we can choose a threshold between 0.5 and 1.

Let's look more into teh steering

In [16]:
overlay_hist(straights, STEER, bin_width=0.25,
             title="Steering (signed), straights only",
             xlabel="steering angle (deg), + = left")

# centre and spread of signed steering on straights, per stint
print(
    straights.groupby("stint")[STEER]
    .describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95])
    .round(2)
)

        count  mean   std    min    5%   25%   50%   75%    95%    max
stint
1      7018.0  1.58  7.12 -50.18 -7.81 -2.09  0.58  4.57  13.86  44.29
2      4844.0  2.82  7.01 -26.00 -8.16 -1.03  3.10  6.00  13.42  36.70

we notice two things:
1. the medin shifter from 0.58 to 3.1 between the two stints (shift of abt ~2.5 degrees)
2. the spread is approx. teh same:
    - 25-75%: 6.7 vs 7.0
    -  7-95%: 21.7 vs 21.6
    - std: 7.12 vs 1.01
    
    so the distribution just moved right by ~2.5. this coule either be teh driver just holding teh steering wheel at that angle on a staight or an offset. we could confirm by checkingthe behavior of the car when the lateral accelration ~0

In [17]:
LAT_ACC = "imu_acceleration__y"
SPEED = "vehicle_speed__u"

AY_STRAIGHT_G = 0.03    # |lateral acc| below this = car not turning
MIN_SPEED_MS = 8.0      # ignore slow points

going_straight = grid[
    (grid[LAT_ACC].abs() < AY_STRAIGHT_G)
    & (grid[SPEED] > MIN_SPEED_MS)
].copy()

overlay_hist(going_straight, STEER, bin_width=0.25,
             title=f"Steering when |lateral acc| < {AY_STRAIGHT_G} g",
             xlabel="steering angle (deg), + = left")

print(
    going_straight.groupby("stint")[STEER]
    .describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95])
    .round(2)
)

# second check: steering vs lateral acc, straight-line fit per stint
# the intercept is the steering reading at zero lateral acc (the zero point)
# steering = intercept + slope × lateral acc
linear_region = grid[(grid[LAT_ACC].abs() < 0.3) & (grid[SPEED] > MIN_SPEED_MS)]
for stint, g in linear_region.groupby("stint"):
    g = g[[LAT_ACC, STEER]].dropna()
    slope, intercept = np.polyfit(g[LAT_ACC], g[STEER], 1)
    print(f"stint {stint}: steering at 0 g = {intercept:.2f} deg, slope = {slope:.1f} deg/g")

        count  mean   std    min    5%   25%   50%   75%   95%    max
stint
1      1110.0 -0.10  7.29 -86.66 -9.57 -1.52  0.20  2.38  8.18  37.32
2       985.0  0.76  6.11 -47.53 -4.72 -0.15  1.34  2.76  5.45  39.74
stint 1: steering at 0 g = -0.02 deg, slope = 23.8 deg/g
stint 2: steering at 0 g = 0.50 deg, slope = 30.1 deg/g

on the straight zones the gap was ~2.5. snce you keep only the moments the car really goes straight, it drops to 0.5–1. so the sensor offset is at most about half a degree to one degree. 

that means most of the 2.5 on the straight zones was the driver.

What the data settled
* throttle off: below ~0.01, a clean spike.
* rake off: below ~0.5–1 bar, the noise spike plus its shoulder.
* steering ~ 0: a band of a few degrees around 0. the sensor offset between stints is <= ~1 , so no correction needed.

In [18]:
EXCLUDE_LAPS = [2]   # lap 2 has the stop, lap 14 (pit) is already off the grid

lap_times = (
    grid[~grid["lap"].isin(EXCLUDE_LAPS)]
    .groupby(["stint", "lap"])["t_lap"].max()
    .rename("lap_time")
    .reset_index()
)
print(lap_times.sort_values(["stint", "lap_time"]).to_string(index=False))

# every stint 1 lap paired with every stint 2 lap, by lap-time difference
s1 = lap_times[lap_times["stint"] == 1]
s2 = lap_times[lap_times["stint"] == 2]
pairs = s1.merge(s2, how="cross", suffixes=("_s1", "_s2"))
pairs["diff_s"] = (pairs["lap_time_s1"] - pairs["lap_time_s2"]).abs()
pairs = pairs.sort_values("diff_s")

# take the 3 closest pairs without reusing a lap
chosen, used = [], set()
for _, row in pairs.iterrows():
    if row["lap_s1"] in used or row["lap_s2"] in used:
        continue
    chosen.append(row)
    used.update([row["lap_s1"], row["lap_s2"]])
    if len(chosen) == 3:
        break

chosen = pd.DataFrame(chosen)[["lap_s1", "lap_time_s1", "lap_s2", "lap_time_s2", "diff_s"]]
print(chosen.round(3).to_string(index=False))

 stint  lap  lap_time
     1   10 60.785960
     1    9 61.179748
     1   12 61.390818
     1    8 61.441157
     1   11 61.455027
     1   13 61.752442
     1    6 62.466132
     1    5 63.384953
     1    7 64.033258
     1    4 65.534067
     1    3 66.969199
     1    1 72.290684
     2   19 61.172134
     2   18 61.423446
     2   21 61.789847
     2   23 62.091767
     2   17 62.944455
     2   22 63.643354
     2   16 63.698641
     2   15 67.156428
     2   20 67.246115
 lap_s1  lap_time_s1  lap_s2  lap_time_s2  diff_s
    9.0       61.180    19.0       61.172   0.008
    8.0       61.441    18.0       61.423   0.018
   13.0       61.752    21.0       61.790   0.037

In [19]:
from plotly.subplots import make_subplots

PAIRS = [(9, 19), (8, 18), (13, 21)]
PAIR_COLORS = ["#1f77b4", "#d62728", "#2ca02c"]

THROTTLE_OFF = 0.01   # from the throttle histogram
BRAKE_OFF = 0.5       # from the brake histogram

# sector boundaries: end of the 9th and 18th corner zones
corner_zones = zones[zones["type"] == "corner"].sort_values("s_start").reset_index(drop=True)
s_end_9 = corner_zones.loc[8, "s_end"]
s_end_18 = corner_zones.loc[17, "s_end"]
SECTORS = {
    1: (0, s_end_9),
    2: (s_end_9, s_end_18),
    3: (s_end_18, track_length),
}

plot_df = grid.copy()
plot_df["abs_steer"] = plot_df[STEER].abs()


def plot_sector(sector, s_min, s_max):
    fig = make_subplots(
        rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,
        subplot_titles=("|Steering| (deg)"),
    )

    for (lap_s1, lap_s2), color in zip(PAIRS, PAIR_COLORS):
        for lap, dash in [(lap_s1, "solid"), (lap_s2, "dash")]:
            d = plot_df[(plot_df["lap"] == lap)
                        & (plot_df["s"] >= s_min) & (plot_df["s"] <= s_max)]
            stint = int(d["stint"].iloc[0])
            name = f"lap {lap} (stint {stint})"
            for row, col in [(1, THROTTLE), (2, BRAKE), (3, "abs_steer")]:
                fig.add_trace(
                    go.Scatter(x=d["s"], y=d[col], mode="lines", name=name,
                               line=dict(color=color, dash=dash, width=1.5),
                               legendgroup=name, showlegend=(row == 1)),
                    row=row, col=1,
                )

    # shade corner zones and label them with their corner number
    for _, z in corner_zones.iterrows():
        if z["s_end"] < s_min or z["s_start"] > s_max:
            continue
        for row in (1, 2, 3):
            fig.add_vrect(x0=z["s_start"], x1=z["s_end"], fillcolor="grey",
                          opacity=0.12, line_width=0, row=row, col=1)
        fig.add_annotation(x=(z["s_start"] + z["s_end"]) / 2, y=1.02, yref="paper",
                           text=f"C{int(z['corner'])}", showarrow=False, font=dict(size=12))

    # off thresholds
    fig.add_hline(y=THROTTLE_OFF, line_dash="dot", line_color="black", row=1, col=1)
    fig.add_hline(y=BRAKE_OFF, line_dash="dot", line_color="black", row=2, col=1)

    fig.update_xaxes(title_text="s (m)", row=3, col=1)
    fig.update_layout(title=f"Sector {sector}  ({s_min:.0f}–{s_max:.0f} m)",
                      height=950, width=1600, font=dict(size=14),
                      hovermode="x unified")
    fig.show()


for sector, (s_min, s_max) in SECTORS.items():
    plot_sector(sector, s_min, s_max)

notice that in the esses there is little braking, the driver brakes going into the first corner of the esses but then he picks up the throttle and stops braking and goes through the other two corners just by lifitng off the throttle to slow down instead of braking. there are some stretches of coasting, the behavior is different between the drivers and even for the same driver between laps, sometimes they brake in certain sections of the track and on another lap they dont they just lift off. but definitely you can notice that the first driver is more aggressive when braking than the second one.

from bserving the driving behavior across the laps and comaring the steering, throttle, and braking, I think it would be best to create a phase named "lift" where the driver lifts off the throttle but does not hit the brakes. this is because the driver uses it instea dof braking, specially around the esses and where the corners are not veyr curved.

we will ocnsider full throttle to be >=0.95 as teh data suggested een though the drivers almost never reaches it. any throttle that s on but not falling and below full is going to be labeled **throttle on**.

just to be on the safe side, any phase where both throttle and brake are rising will be labelled "??" because literally how? we don't expect to see this but you never know

the other phases will be:
* trail braking: braking and steering
* braking: braking with no steering (throttle is lifting or off)
* full throttle: throttle > 0.95
* coasting: throttle and brake are both off
* lifting: throttle is fallin with no braking
* throttle on: throttle not falling, below full (basically when on a straight but it's below 0.95)

from the histograms above, the throttle is considered "off" when it's <= 0.1, and the brake is off when it's < 0.5 (sensor noise)

|steering| <= 10 degrees to be considered steering ~0 because when the car was going straight, abt 90% of the steering readings fell within +/-10 degrees in both stints. so 10 degrees covers normal straight line steering fro both drivers without labelling it as cornering. this could result in gentle cornering to be consdidered "straight", specifically in stint 2 but if we make it tighter then it would misclassify stint 1's straights.

the rate change is next, because sensors jitter a lot, for example when a steering is held straigh the value tends to jump up and down by a value, like +/- 5 degrees. same thing for throttle and the brake pressure. so let's look at the rate change over two similar laps. let's take the lap in distance (m) not in time so we can see how the rate changes in unit/m

In [20]:
GRID_STEP_M = 0.3
SMOOTH_M = 2.4 # smoothing window in metres
PAIR = (9, 19) # stint 1 lap, stint 2 lap
LAP_COLORS = {PAIR[0]: "#1f77b4", PAIR[1]: "#ff7f0e"}
LAP_DASH = {PAIR[0]: "solid", PAIR[1]: "dash"}

window = max(1, int(round(SMOOTH_M / GRID_STEP_M)))

RATE_SIGNALS = {
    "throttle": (THROTTLE, "throttle rate (1/m)"),
    "brake": (BRAKE, "brake rate (bar/m)"),
    "steer": ("abs_steer", "|steering| rate (deg/m)"),
}


def lap_rates(lap):
    """Raw and smoothed per-metre rates for one lap."""
    d = plot_df[plot_df["lap"] == lap].sort_values("s").copy()
    for key, (col, _) in RATE_SIGNALS.items():
        raw = d[col].to_numpy()
        smooth = (d[col].rolling(window, center=True, min_periods=1)
                  .mean().to_numpy())
        d[f"{key}_rate_raw"] = np.gradient(raw, d["s"].to_numpy())
        d[f"{key}_rate_smooth"] = np.gradient(smooth, d["s"].to_numpy())
    return d


rates = {lap: lap_rates(lap) for lap in PAIR}


def plot_rates_sector(sector, s_min, s_max):
    fig = make_subplots(
        rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.04,
        subplot_titles=[label for _, label in RATE_SIGNALS.values()],
    )

    for lap in PAIR:
        d = rates[lap]
        d = d[(d["s"] >= s_min) & (d["s"] <= s_max)]
        stint = int(d["stint"].iloc[0])
        for row, key in enumerate(RATE_SIGNALS, start=1):
            fig.add_trace(
                go.Scatter(x=d["s"], y=d[f"{key}_rate_raw"], mode="lines",
                           name=f"lap {lap} (stint {stint}) raw",
                           line=dict(color=LAP_COLORS[lap], width=0.8,
                                     dash=LAP_DASH[lap]),
                           opacity=0.35,
                           legendgroup=f"{lap}raw", showlegend=(row == 1)),
                row=row, col=1,
            )
            fig.add_trace(
                go.Scatter(x=d["s"], y=d[f"{key}_rate_smooth"], mode="lines",
                           name=f"lap {lap} (stint {stint}) smoothed {SMOOTH_M:g} m",
                           line=dict(color=LAP_COLORS[lap], width=2.2,
                                     dash=LAP_DASH[lap]),
                           legendgroup=f"{lap}smooth", showlegend=(row == 1)),
                row=row, col=1,
            )

    for _, z in corner_zones.iterrows():
        if z["s_end"] < s_min or z["s_start"] > s_max:
            continue
        for row in (1, 2, 3):
            fig.add_vrect(x0=z["s_start"], x1=z["s_end"], fillcolor="grey",
                          opacity=0.12, line_width=0, row=row, col=1)
        fig.add_annotation(x=(z["s_start"] + z["s_end"]) / 2, y=1.02, yref="paper",
                           text=f"C{int(z['corner'])}", showarrow=False,
                           font=dict(size=12))

    for row in (1, 2, 3):
        fig.add_hline(y=0, line_dash="dot", line_color="black", row=row, col=1)

    fig.update_xaxes(title_text="s (m)", row=3, col=1)
    fig.update_layout(
        title=f"Rates, sector {sector} ({s_min:.0f}–{s_max:.0f} m), laps {PAIR[0]} vs {PAIR[1]}",
        height=950, width=1600, font=dict(size=14), hovermode="x unified",
    )
    fig.show()


for sector, (s_min, s_max) in SECTORS.items():
    plot_rates_sector(sector, s_min, s_max)

after experimenting with multiple values for the smoothing rate, i think the value of 2.4m is decet (so with the grid being 0.3m that is 8 grid points) is decent enough to flatten the areas with jitter to settle around 0 and at the same time keep the the trend where there is actual change (turning, braking, pushing on a straight) valid.

next, i will investiate what could be considered a good value for the deadband, i.e. the rate change for each of these sensr values that will be considered negligible, sensor noice. for example, if the steering jumps up x degrees in an area where it should be steady, then we still consider the steering value to be the same across that period and neglect that change. hope that makes sense.

for the steering, we will look at the steering behavior when the car is on a straight. for the braking and the throttle we will look at the data when the driver is applying them

In [21]:
SMOOTH_M = 2.4
EXCLUDE_LAPS = [2] # standstills

LAT_ACC = "imu_acceleration__y"
SPEED = "vehicle_speed__u"


def add_rates(df, smooth_m=SMOOTH_M):
    """Per-lap smoothed per-metre rates for throttle, brake and |steering|."""
    w = max(1, int(round(smooth_m / GRID_STEP_M)))
    out = []
    for lap, d in df.groupby("lap"):
        d = d.sort_values("s").copy()
        s = d["s"].to_numpy()
        for col, key in [(THROTTLE, "thr"), (BRAKE, "brk"), ("abs_steer", "str")]:
            smooth = d[col].rolling(w, center=True, min_periods=1).mean()
            d[f"{key}_rate"] = np.gradient(smooth.to_numpy(), s)
        out.append(d)
    return pd.concat(out)


rated = add_rates(plot_df[~plot_df["lap"].isin(EXCLUDE_LAPS)])

# method 1: steering wobble when the car is really going straight 
held_straight = rated[
    (rated["type"] == "straight")
    & (rated[LAT_ACC].abs() < 0.03)
    & (rated[SPEED] > 8.0)
]
print("Method 1, |steering rate| (deg/m) when going straight")
print(
    held_straight.groupby("stint")["str_rate"]
    .apply(lambda r: r.abs().quantile([0.5, 0.9, 0.95, 0.99]))
    .unstack().round(2)
)
print("all:", held_straight["str_rate"].abs().quantile([0.5, 0.9, 0.95, 0.99]).round(2).to_dict())


# method 2: histogram of the rate where the signal is on 
def rate_hist(data, col, bin_width, x_max, title, xlabel):
    fig = go.Figure()
    for stint, g in data.groupby("stint"):
        fig.add_trace(go.Histogram(
            x=g[col].dropna(),
            xbins=dict(start=-x_max, end=x_max, size=bin_width),
            histnorm="percent", opacity=0.5, name=f"stint {stint}",
            marker_color=STINT_COLORS.get(stint),
        ))
    fig.add_vline(x=0, line_dash="dot", line_color="black")
    fig.update_layout(title=title, xaxis_title=xlabel,
                      yaxis_title="% of points in the stint",
                      barmode="overlay", height=650, width=1600, font=dict(size=14))
    fig.update_xaxes(range=[-x_max, x_max])
    fig.show()


rate_hist(rated[rated[THROTTLE] > THROTTLE_OFF], "thr_rate",
          bin_width=0.002, x_max=0.3,
          title=f"Throttle rate where throttle is on (smoothing {SMOOTH_M} m)",
          xlabel="throttle rate (1/m)")

rate_hist(rated[rated[BRAKE] > BRAKE_OFF], "brk_rate",
          bin_width=0.1, x_max=6,
          title=f"Brake rate where brake is on (smoothing {SMOOTH_M} m)",
          xlabel="brake rate (bar/m)")

rate_hist(rated, "str_rate",
          bin_width=0.5, x_max=40,
          title=f"|Steering| rate, all points (smoothing {SMOOTH_M} m)",
          xlabel="|steering| rate (deg/m)")

Method 1, |steering rate| (deg/m) when going straight
       0.50  0.90  0.95  0.99
stint
1      0.29  1.57  2.43  5.70
2      0.25  1.11  1.65  5.02
all: {0.5: 0.27, 0.9: 1.39, 0.95: 2.06, 0.99: 5.61}

the first and second method agree for the steering deadband to be ~+/-2.5deg/m. as for the brake, from eyeballing it it looks like most jitter is about 1bar/m and for the throttle it looks like it's about 0.02/m.

let's try to find the width of the central peak and see if we mathematically backup the claims of methods 2. to do that we use the median absolute deviation (MAD)

In [22]:
def mad_deadband(rate):
    """Robust width of the central peak of a rate distribution."""
    r = rate.dropna()
    mad = (r - r.median()).abs().median()
    spread = 1.4826 * mad
    return pd.Series({"spread": spread, "2x": 2 * spread, "3x": 3 * spread})


print("Method 3: MAD-based deadband on the 'on' points")
print(pd.DataFrame({
    "throttle (1/m)": mad_deadband(rated.loc[rated[THROTTLE] > THROTTLE_OFF, "thr_rate"]),
    "brake (bar/m)": mad_deadband(rated.loc[rated[BRAKE] > BRAKE_OFF, "brk_rate"]),
    "steering (deg/m)": mad_deadband(rated["str_rate"]),
}).round(3))

print("\nBrake noise floor: |brake rate| where brake is off (bar/m)")
print(rated.loc[rated[BRAKE] <= BRAKE_OFF, "brk_rate"].abs()
      .quantile([0.5, 0.9, 0.95, 0.99]).round(3).to_dict())

Method 3: MAD-based deadband on the 'on' points
        throttle (1/m)  brake (bar/m)  steering (deg/m)
spread            0.02          1.117             2.237
2x                0.04          2.235             4.474
3x                0.06          3.352             6.711

Brake noise floor: |brake rate| where brake is off (bar/m)
{0.5: 0.0, 0.9: 0.035, 0.95: 0.296, 0.99: 1.204}

* throttle: the spread is 0.02 so it confirms what we saw in the plot.
* brake: the spread is 1.1, close to the 1bar/m we decided on, the noise in teh brake when the brake is off is around 0.3bar but that should not affect here because we took the brake phase to only include to be >0.5
* steering:  the value we chose (2.5) sit above the 2.2deg/m that we eyeballed but it's close enough.

the reason why i'm only paying attention to the 1x spread and not to the 1-3x is because the core of the rate distribution includes slow real movements, so the spread itself, checked against teh steering value since we know the deadband for it from method 1 and method 2, we can generalize over the pedals and assume that the spread is the deadband.

the values we finally settle for the deadband is:
* steering +/-2.5 deg/m 
* brake +/-1 bar/m 
* throttle +/-0.02 /m

next, we need to decide on what's the minimum distance for a phase so that we have clean phases, we don't want to have 200 mini exists scattered around the track bc the conditions are met for .5 meters.

In [ ]:
GRID_STEP_M = 0.3
SMOOTH_M = 2.4

THROTTLE_OFF = 0.01
THROTTLE_FULL = 0.95
BRAKE_OFF = 0.5
STEER_ZERO_DEG = 10.0

# deadbands we agreed on
DB_THROTTLE = 0.02
DB_BRAKE = 1.0
DB_STEER = 2.5
EXCLUDE_LAPS = [2]

In [33]:
def label_phases(df):
    """Assign one phase per grid point, first matching rule wins.
    Phases: ??, trail braking, braking, full throttle, coasting, lift, throttle on."""
    thr, brk, st = df[THROTTLE], df[BRAKE], df["abs_steer"]

    brake_on = brk > BRAKE_OFF
    thr_on = thr > THROTTLE_OFF
    full = thr >= THROTTLE_FULL
    steer_zero = st <= STEER_ZERO_DEG

    thr_rising = df["thr_rate"] > DB_THROTTLE
    thr_falling = df["thr_rate"] < -DB_THROTTLE
    brk_rising = df["brk_rate"] > DB_BRAKE
    brk_falling = df["brk_rate"] < -DB_BRAKE
    st_rising = df["str_rate"] > DB_STEER

    any_nan = df[[THROTTLE, BRAKE, "abs_steer",
                  "thr_rate", "brk_rate", "str_rate"]].isna().any(axis=1)

    conditions = [
        any_nan,
        brake_on & brk_rising & thr_on & thr_rising,             # ??
        brake_on & (~steer_zero | (brk_falling & st_rising)),    # trail braking
        brake_on,                                                # braking
        full,                                                    # full throttle
        ~thr_on & ~brake_on,                                     # coasting
        thr_falling & ~brake_on,                                 # lift
    ]
    choices = ["__nan__", "??", "trail braking", "braking", "full throttle",
               "coasting", "lift"]

    phase = np.select(conditions, choices, default="throttle on")
    df = df.copy()
    df["phase"] = pd.Series(phase, index=df.index).replace("__nan__", np.nan)
    return df

In [34]:
def phase_runs(df):
    """Consecutive stretches of the same phase within each lap, with their length."""
    rows = []
    for lap, d in df.groupby("lap"):
        d = d.sort_values("s")
        run_id = (d["phase"] != d["phase"].shift()).cumsum()
        g = d.groupby(run_id).agg(phase=("phase", "first"),
                                  stint=("stint", "first"),
                                  s_start=("s", "first"),
                                  s_end=("s", "last"),
                                  n_points=("s", "size"))
        g["lap"] = lap
        rows.append(g)
    runs = pd.concat(rows, ignore_index=True).dropna(subset=["phase"])
    runs["length_m"] = runs["n_points"] * GRID_STEP_M
    return runs

In [35]:
plot_df = grid.copy()
plot_df["abs_steer"] = plot_df[STEER].abs()
labelled = label_phases(add_rates(plot_df[~plot_df["lap"].isin(EXCLUDE_LAPS)]))
runs = phase_runs(labelled)

n_laps = labelled["lap"].nunique()
print(f"{len(runs)} runs over {n_laps} laps = one phase change every "
      f"{n_laps * 805 / len(runs):.1f} m on average\n")

summary = runs.groupby("phase").apply(lambda g: pd.Series({
    "runs": len(g),
    "median_m": g["length_m"].median(),
    "% runs < 1 m": (g["length_m"] < 1).mean() * 100,
    "% runs < 2 m": (g["length_m"] < 2).mean() * 100,
    "% distance in runs < 1 m": g.loc[g["length_m"] < 1, "length_m"].sum() / g["length_m"].sum() * 100,
    "% distance in runs < 2 m": g.loc[g["length_m"] < 2, "length_m"].sum() / g["length_m"].sum() * 100,
})).round(1)
print(summary.sort_values("runs", ascending=False).to_string())

fig = go.Figure()
for phase, g in runs.groupby("phase"):
    fig.add_trace(go.Histogram(x=g["length_m"], name=phase,
                               xbins=dict(start=0, end=20, size=GRID_STEP_M)))
for x in (1, 2):
    fig.add_vline(x=x, line_dash="dot", line_color="black")
fig.update_layout(title="Phase run lengths, all laps, final parameters",
                  xaxis_title="run length (m)", yaxis_title="number of runs",
                  barmode="stack", height=650, width=1600, font=dict(size=14))
fig.update_xaxes(range=[0, 20])
fig.show()

3333 runs over 21 laps = one phase change every 5.1 m on average

                 runs  median_m  % runs < 1 m  % runs < 2 m  % distance in runs < 1 m  % distance in runs < 2 m
phase
throttle on    1227.0       5.1           9.4          19.6                       0.7                       2.8
lift            639.0       2.1          20.5          46.6                       5.5                      24.2
coasting        556.0       2.1          25.9          48.9                       4.3                      14.1
trail braking   544.0       3.3          18.2          31.4                       2.9                       8.7
braking         367.0       3.0          28.3          42.2                       2.7                       6.0

finally, this is what we settled on so far:
* Levels: throttle off < 0.01, full >= 0.95, brake off < 0.5 bar, steering ~ 0 at <=> 10deg
* Smoothing: 2.4 m for all signals
* Deadbands: steering +/-2.5 deg/m, throttle +/-0.02 /m, brake +/-1 bar/m
* Minimum phase length: 1 m (from the graph above it looks like a good cutoff)
* Phases, in priority order: ??, trail braking, braking, full throttle, coasting, lift, throttle on

In [39]:
def label_phases(df):
    """Assign one phase per grid point, first matching rule wins.
    Phases: ??, trail braking, braking, full throttle, coasting, lift, throttle on."""
    thr, brk, st = df[THROTTLE], df[BRAKE], df["abs_steer"]

    brake_on = brk > BRAKE_OFF
    thr_on = thr > THROTTLE_OFF
    full = thr >= THROTTLE_FULL
    steer_zero = st <= STEER_ZERO_DEG

    thr_rising = df["thr_rate"] > DB_THROTTLE
    thr_falling = df["thr_rate"] < -DB_THROTTLE
    brk_rising = df["brk_rate"] > DB_BRAKE
    brk_falling = df["brk_rate"] < -DB_BRAKE
    st_rising = df["str_rate"] > DB_STEER

    any_nan = df[[THROTTLE, BRAKE, "abs_steer",
                  "thr_rate", "brk_rate", "str_rate"]].isna().any(axis=1)

    conditions = [
        any_nan,
        brake_on & brk_rising & thr_on & thr_rising,             # ??
        brake_on & (~steer_zero | (brk_falling & st_rising)),    # trail braking
        brake_on,                                                # braking
        full,                                                    # full throttle
        ~thr_on & ~brake_on,                                     # coasting
        thr_falling & ~brake_on,                                 # lift
    ]
    choices = ["__nan__", "??", "trail braking", "braking", "full throttle",
               "coasting", "lift"]

    phase = np.select(conditions, choices, default="throttle on")
    df = df.copy()
    df["phase"] = pd.Series(phase, index=df.index).replace("__nan__", np.nan)
    return df

In [ ]:
X_COL = "vehicle_position__x"
Y_COL = "vehicle_position__y"

PHASE_COLORS = {
    "braking": "#1f3fbf", "trail braking": "#e377c2", "coasting": "#d62728",
    "lift": "#ff7f0e", "full throttle": "#000000", "throttle on": "#17becf",
    "??": "#7f7f7f",
}


def plot_track_phases(df, laps, col="phase"):
    """One track map per lap, each grid point coloured by its phase."""
    laps = list(laps)
    fig = make_subplots(rows=1, cols=len(laps), horizontal_spacing=0.03,
                        subplot_titles=[f"Lap {lap} (stint {int(df.loc[df['lap'] == lap, 'stint'].iloc[0])})"
                                        for lap in laps])

    main = apexes[apexes["is_main"]]
    shown = set()
    for i, lap in enumerate(laps, start=1):
        d = df[df["lap"] == lap].sort_values("s")

        # corner numbers at the main apexes
        fig.add_trace(go.Scatter(x=main["x"], y=main["y"], mode="text",
                                 text=[f"C{int(c)}" for c in main["corner"]],
                                 textfont=dict(size=12, color="#333333"),
                                 hoverinfo="skip", showlegend=False),
                      row=1, col=i)

        for phase, g in d.groupby(col):
            fig.add_trace(go.Scatter(
                x=g[X_COL], y=g[Y_COL], mode="markers",
                marker=dict(size=4, color=PHASE_COLORS.get(phase, "#bbbbbb")),
                name=phase, legendgroup=phase, showlegend=phase not in shown,
                customdata=g["s"],
                hovertemplate=f"{phase}<br>s = %{{customdata:.1f}} m<extra></extra>",
            ), row=1, col=i)
            shown.add(phase)

        # equal scale on both axes so the track isn't stretched
        xref = "x" if i == 1 else f"x{i}"
        fig.update_yaxes(scaleanchor=xref, scaleratio=1, row=1, col=i)

    fig.update_xaxes(showgrid=False, zeroline=False, showticklabels=False)
    fig.update_yaxes(showgrid=False, zeroline=False, showticklabels=False)
    fig.update_layout(
        title="Phases on track",
        height=900, width=800 * len(laps), font=dict(size=14),
        showlegend=True,
        legend=dict(orientation="h", x=0.5, xanchor="center", y=1.12,
                    itemsizing="constant", font=dict(size=15)),
        margin=dict(t=150),
    )
    fig.show()


plot_track_phases(labelled, [9, 19])

the empty parts are bc of NaN values

after adding the code in segemnt.py, we will test it

In [4]:
from src.config import PROC_DATA, DISTANCE_GRID_STEP_M
from src.segment import load_segmented, SEGMENT_FILES

In [5]:
data = load_segmented()

In [6]:
for name, file in SEGMENT_FILES.items():
    print(f"{name:12s} {file:22s} exists: {(PROC_DATA / file).exists()}  rows: {len(data[name])}")

grid = data["grid"]

grid         grid_phases.parquet    exists: True  rows: 59048
laps         laps.parquet           exists: True  rows: 23
gaps         gaps.parquet           exists: True  rows: 55
zones        zones.parquet          exists: True  rows: 32
apexes       apexes.parquet         exists: True  rows: 30
stints       stints.parquet         exists: True  rows: 2
standstills  standstills.parquet    exists: True  rows: 9

In [7]:
# structure checks: should match what the notebook gave
print("\nlaps in laps table:", len(data["laps"]))                 # expect 23
print("laps on the grid:", grid["lap"].nunique())                 # expect 22 (pit lap 14 excluded)
print("rows per lap:", grid.groupby("lap").size().unique())       # expect one value, 2684
print("zones:", len(data["zones"]), "| apexes:", len(data["apexes"]))  # expect 32 | 30
print("stints:", len(data["stints"]))                              # expect 2

laps in laps table: 23
laps on the grid: 22
rows per lap: [2684]
zones: 32 | apexes: 30
stints: 2

In [8]:
# phase checks
print("\npoints per phase:")
print(grid["phase"].value_counts(dropna=False))
print(f"\npoints without a phase: {grid['phase'].isna().mean() * 100:.2f}%")

share = (grid.dropna(subset=["phase"])
         .groupby(["stint", "phase"]).size()
         .groupby(level="stint").transform(lambda x: x / x.sum() * 100)
         .unstack("stint").round(1))
print("\n% of distance in each phase, per stint")
print(share.to_string())

points per phase:
phase
throttle on      31164
braking           7712
coasting          6753
trail braking     6691
lift              4767
NaN               1961
Name: count, dtype: int64

points without a phase: 3.32%

% of distance in each phase, per stint
stint             1     2
phase
braking        16.0   9.9
coasting        6.5  19.5
lift            8.9   7.6
throttle on    54.5  54.7
trail braking  14.1   8.2

In [10]:
g = grid[grid["lap"] != 2].sort_values(["lap", "s"])

change = (g["phase"].fillna("__nan__") != g["phase"].fillna("__nan__").shift()) | (g["lap"] != g["lap"].shift())
runs = g.assign(run_id=change.cumsum()).groupby("run_id").agg(phase=("phase", "first")).dropna()

print("total runs:", len(runs))            # shuld be 3333
print(runs["phase"].value_counts())        # should be 1227, 639, 556, 544, 367

total runs: 3333
phase
throttle on      1227
lift              639
coasting          556
trail braking     544
braking           367
Name: count, dtype: int64

Values Match! Confirmed!