In [4]:
from src.config import PIT_MIN_S, PROC_DATA
import pandas as pd
from src.preprocess import load_processed

In [7]:
df = load_processed()
df

,t_s,hv_power__power,imu_angular_rate__x,imu_angular_rate__y,imu_angular_rate__z,imu_acceleration__x,imu_acceleration__y,imu_acceleration__z,vehicle_position__x,vehicle_position__y,...,pedal_brakes_pressure__front,pedal_brakes_pressure__rear,pedal_throttle__throttle,steer_angle__angle,front_angular_velocity__fl,front_angular_velocity__fr,inv_r_id_a8_n_actual_filt__n_act_filt,inv_l_id_a8_n_actual_filt__n_act_filt,inv_r_id_27_iq_actual__iq_act_filt,inv_l_id_27_iq_actual__iq_act_filt
0,2.188702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.192702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
2,2.196702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
3,2.200702,0.131650,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
4,2.204702,0.121386,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.109383,0.051784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551187,2206.936702,-0.001526,-0.190444,-0.052721,-0.000712,0.002248,-0.020000,-0.983122,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,0.031180,0.000000
551188,2206.940702,-0.001526,-0.146536,-0.043939,-0.070965,0.002248,-0.012936,-0.968809,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.029027,0.000000
551189,2206.944702,-0.001526,-0.082120,-0.236204,-0.053140,0.002248,-0.016021,-0.953979,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551190,2206.948702,-0.001526,-0.142615,-0.047344,-0.044080,0.007444,-0.020000,-0.970781,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551191,2206.952702,-0.001526,-0.004415,-0.041300,-0.001003,0.012248,-0.015721,-0.981442,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000

In [25]:
df.columns

Index(['t_s', 'hv_power__power', 'imu_angular_rate__x', 'imu_angular_rate__y',
       'imu_angular_rate__z', 'imu_acceleration__x', 'imu_acceleration__y',
       'imu_acceleration__z', 'vehicle_position__x', 'vehicle_position__y',
       'vehicle_position__heading', 'vehicle_speed__u', 'vehicle_speed__v',
       'vehicle_curvilinear_coordinates__s',
       'vehicle_curvilinear_coordinates__n', 'pedal_brakes_pressure__front',
       'pedal_brakes_pressure__rear', 'pedal_throttle__throttle',
       'steer_angle__angle', 'front_angular_velocity__fl',
       'front_angular_velocity__fr', 'inv_r_id_a8_n_actual_filt__n_act_filt',
       'inv_l_id_a8_n_actual_filt__n_act_filt',
       'inv_r_id_27_iq_actual__iq_act_filt',
       'inv_l_id_27_iq_actual__iq_act_filt'],
      dtype='str')

In [8]:
df["vehicle_curvilinear_coordinates__s"]

0         790.998673
1         790.998673
2         790.998673
3         790.998673
4         790.998673
             ...
551187    736.999598
551188    736.999598
551189    736.999598
551190    736.999598
551191    736.999598
Name: vehicle_curvilinear_coordinates__s, Length: 551192, dtype: float64

In [10]:
from src.utils import find_standstills
standstills = find_standstills()

In [11]:
standstills

       start_s        end_s  duration_s
0     0.000000    13.002358   13.002358
1    20.790024    54.929918   34.139894
2   161.421000   176.054854   14.633854
3   192.778036   206.897613   14.119577
4   227.119072   242.465951   15.346879
5   977.176868  1157.391011  180.214143
6  1163.760712  1196.196530   32.435818
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [19]:
pit_cand = standstills[standstills["duration_s"] >= PIT_MIN_S]
pit_cand

       start_s        end_s  duration_s
5   977.176868  1157.391011  180.214143
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [14]:
from src.utils import find_laps
raw_laps = find_laps()

In [15]:
raw_laps

,lap_number,start_s,end_s,lap_time_s,has_stop,has_gap,has_pit,is_out_lap,valid
0,1,61.447598,133.758730,72.311132,False,False,False,False,True
1,2,133.758730,281.465908,147.707178,True,False,False,False,False
2,3,281.465908,348.448507,66.982599,False,False,False,False,True
3,4,348.448507,413.994435,65.545928,False,False,False,False,True
4,5,413.994435,477.396409,63.401974,False,False,False,False,True
5,6,477.396409,539.871968,62.475559,False,False,False,False,True
6,7,539.871968,603.920050,64.048082,False,True,False,False,False
7,8,603.920050,665.375170,61.455120,False,False,False,False,True
8,9,665.375170,726.564443,61.189273,False,True,False,False,False
9,10,726.564443,787.367604,60.803161,False,True,False,False,False
10,11,787.367604,848.838904,61.471300,False,True,False,False,False
11,12,848.838904,910.240131,61.401227,False,False,False,False,True
12,13,910.240131,972.009224,61.769093,False,False,False,False,True
13,14,972.009224,1203.733071,231.723847,True,True,True,True,False
14,15,1203.733071,1270.906110,67.173039,False,False,False,False,True
15,16,1270.906110,1334.621896,63.715786,False,True,False,False,False
16,17,1334.621896,1397.577341,62.955445,False,False,False,False,True
17,18,1397.577341,1459.020535,61.443194,False,False,False,False,True
18,19,1459.020535,1520.200158,61.179623,False,False,False,False,True
19,20,1520.200158,1587.460414,67.260256,False,False,False,False,True
20,21,1587.460414,1649.263642,61.803228,False,True,False,False,False
21,22,1649.263642,1712.916918,63.653276,False,False,False,False,True
22,23,1712.916918,1775.022498,62.105580,False,False,False,False,True

In [18]:
race_start_t = raw_laps["start_s"].iloc[0]
race_end_t = raw_laps["end_s"].iloc[-1]

In [21]:
pits = pit_cand[(pit_cand["start_s"] > race_start_t) & (pit_cand["end_s"] < race_end_t)]

In [22]:
pits

      start_s        end_s  duration_s
5  977.176868  1157.391011  180.214143

In [23]:
for i in range(len(pits)):
    stint_i = i +1
    stints = {
        stint_i : [pits["start_s"].iloc[i], pits["end_s"].iloc[i]]
    }

In [24]:
stints

{1: [np.float64(977.176868), np.float64(1157.391011)]}

In [1]:
from src.segment import find_segment_standstills

In [2]:
std = find_segment_standstills()
std

       start_s        end_s  duration_s
0     2.216702    13.008702      10.792
1    20.776702    54.928702      34.152
2   161.416702   176.068702      14.652
3   192.732702   206.908702      14.176
4   227.108702   242.484702      15.376
5   977.172702  1157.396702     180.224
6  1163.760702  1196.200702      32.440
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [5]:
pits_cand = std[std["duration_s"] >= PIT_MIN_S]
pits_cand

       start_s        end_s  duration_s
5   977.172702  1157.396702     180.224
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [18]:
df = load_processed()

In [27]:
data = df[(~df["front_angular_velocity__fl"].isna()) & (~df["front_angular_velocity__fr"].isna())]

In [29]:
data["front_angular_velocity__fr"]

7        -0.003052
8        -0.003052
9        -0.003052
10       -0.003052
11       -0.003052
            ...
551187   -0.003052
551188   -0.003052
551189   -0.003052
551190   -0.003052
551191   -0.003052
Name: front_angular_velocity__fr, Length: 544294, dtype: float64

In [1]:
from src.preprocess import load_processed
from src.loader import load_centerline
from src.segment import classify_standstills, define_stints, segment_laps
from src.utils import find_laps

In [2]:
df = load_processed()
track_length = load_centerline().attrs["length"]

In [3]:
standstills = classify_standstills(df)

In [4]:
df, stints = define_stints(df, track_length)

In [5]:
df, laps, gaps = segment_laps(df, standstills, track_length)

In [6]:
standstills

       start_s        end_s  duration_s  type
0     2.216702    13.008702      10.792  stop
1    20.776702    54.928702      34.152  stop
2   161.416702   176.068702      14.652  stop
3   192.732702   206.908702      14.176  stop
4   227.108702   242.484702      15.376  stop
5   977.172702  1157.396702     180.224   pit
6  1163.760702  1196.200702      32.440  stop
7  1829.972702  1908.044702      78.072   pit
8  1920.548702  2206.952702     286.404   pit

In [7]:
laps

    lap  stint      t_start        t_end  lap_time  has_pit  has_stop  has_gap
0     1      1    61.448702   133.748702    72.300    False     False     True
1     2      1   133.752702   281.456702   147.704    False      True     True
2     3      1   281.460702   348.440702    66.980    False     False     True
3     4      1   348.444702   413.988702    65.544    False     False     True
4     5      1   413.992702   477.384702    63.392    False     False     True
5     6      1   477.388702   539.864702    62.476    False     False     True
6     7      1   539.868702   603.916702    64.048    False     False     True
7     8      1   603.920702   665.368702    61.448    False     False     True
8     9      1   665.372702   726.560702    61.188    False     False     True
9    10      1   726.564702   787.360702    60.796    False     False     True
10   11      1   787.364702   848.828702    61.464    False     False     True
11   12      1   848.832702   910.232702    61.400    False     False     True
12   13      1   910.236702   972.000702    61.764    False     False     True
13   14      1   972.004702  1203.728702   231.724     True      True     True
14   15      2  1203.732702  1270.900702    67.168    False     False     True
15   16      2  1270.904702  1334.612702    63.708    False     False     True
16   17      2  1334.616702  1397.572702    62.956    False     False    False
17   18      2  1397.576702  1459.008702    61.432    False     False     True
18   19      2  1459.012702  1520.192702    61.180    False     False     True
19   20      2  1520.196702  1587.452702    67.256    False     False     True
20   21      2  1587.456702  1649.256702    61.800    False     False     True
21   22      2  1649.260702  1712.912702    63.652    False     False     True
22   23      2  1712.916702  1775.016702    62.100    False     False     True

In [8]:
gaps

    lap      t_start        t_end  duration_s     s_start       s_end
0     1   125.692702   125.988702       0.296  737.453005  737.770052
1     2   200.528702   200.572702       0.044  367.187395  367.186090
2     3   304.284702   304.404702       0.120  307.455988  307.750789
3     3   340.380702   340.456702       0.076  731.804109  732.068306
4     4   371.228702   371.676702       0.448  314.291650  314.684471
5     4   376.220702   376.500702       0.280  378.396287  379.034396
6     4   407.488702   407.992702       0.504  749.095514  749.665542
7     5   439.184702   439.500702       0.316  364.115051  364.519274
8     6   504.192702   504.240702       0.048  386.131779  386.309847
9     7   596.276702   597.600702       1.324  737.607516  738.481427
10    8   616.348702   616.424702       0.076  176.376896  176.661068
11    8   652.448702   652.524702       0.076  670.498173  670.747850
12    9   688.540702   688.624702       0.084  350.278746  350.595905
13    9   689.656702   691.684702       2.028  369.740145  371.149244
14    9   714.656702   714.700702       0.044  692.172323  692.473912
15    9   719.656702   719.768702       0.112  742.336665  742.577082
16   10   749.664702   749.760702       0.096  361.048840  361.318852
17   10   754.656702   756.824702       2.168  419.713178  420.390584
18   10   759.660702   759.688702       0.028  482.025529  482.221249
19   10   764.660702   764.692702       0.032  546.443222  546.642252
20   10   779.664702   779.708702       0.044  734.037465  734.204612
21   11   789.656702   789.684702       0.028   32.419537   32.650060
22   11   809.664702   810.928702       1.264  339.577757  340.682546
23   11   814.664702   815.180702       0.516  400.981866  401.522834
24   11   824.752702   824.916702       0.164  528.129443  528.412484
25   12   854.656702   854.688702       0.032   95.855842   96.129679
26   12   896.676702   896.860702       0.184  663.565938  663.858078
27   12   904.660702   904.724702       0.064  756.042893  756.242699
28   13   932.768702   932.972702       0.204  336.602259  337.172448
29   13   944.664702   944.712702       0.048  489.425168  489.626273
30   13   959.664702   959.716702       0.052  692.559496  692.875990
31   13   968.864702   968.944702       0.080  780.226786  780.395555
32   14   994.920702   995.124702       0.204  800.538839  800.538638
33   14   999.924702  1000.160702       0.236  800.491654  800.493839
34   14  1039.928702  1039.960702       0.032  800.229025  800.229025
35   14  1044.928702  1044.956702       0.028  800.194572  800.194572
36   14  1059.920702  1059.952702       0.032  800.270543  800.270527
37   14  1064.928702  1064.960702       0.032  799.351121  799.347091
38   14  1071.532702  1072.184702       0.652  798.714289  798.712009
39   14  1144.472702  1144.552702       0.080  798.999921  798.999921
40   14  1149.928702  1150.476702       0.548  798.999921  798.999921
41   14  1174.920702  1174.956702       0.036  791.488256  791.489083
42   15  1219.920702  1219.988702       0.068  196.958112  197.435891
43   15  1249.180702  1249.396702       0.216  588.614490  589.047039
44   15  1249.928702  1249.992702       0.064  599.345555  599.546190
45   15  1269.920702  1269.988702       0.068  795.208347  795.386196
46   16  1306.144702  1306.888702       0.744  487.577976  488.102370
47   18  1425.068702  1425.160702       0.092  399.107358  399.321015
48   19  1461.152702  1461.260702       0.108   32.262678   32.486919
49   19  1492.120702  1492.204702       0.084  483.751191  483.999942
50   20  1528.484702  1528.564702       0.080  122.641639  122.774092
51   21  1616.356702  1616.620702       0.264  428.659605  429.083990
52   21  1621.360702  1627.572702       6.212  494.240890  494.578953
53   22  1704.604702  1704.692702       0.088  729.044474  729.180763
54   23  1740.448702  1740.536702       0.088  404.372066  404.602450

In [9]:
# check: lap boundaries around the pit (flicker at ~973 s should not be a boundary)
laps[(laps["t_end"] > 900) & (laps["t_start"] < 1300)]

    lap  stint      t_start        t_end  lap_time  has_pit  has_stop  has_gap
11   12      1   848.832702   910.232702    61.400    False     False     True
12   13      1   910.236702   972.000702    61.764    False     False     True
13   14      1   972.004702  1203.728702   231.724     True      True     True
14   15      2  1203.732702  1270.900702    67.168    False     False     True
15   16      2  1270.904702  1334.612702    63.708    False     False     True

In [10]:
# lap times vs section 1 (raw data)
old = find_laps()
cmp = laps[["lap", "lap_time"]].merge(old[["lap_number", "lap_time_s"]],
                                      left_on="lap", right_on="lap_number")
cmp["diff_s"] = cmp["lap_time"] - cmp["lap_time_s"]
cmp

    lap  lap_time  lap_number  lap_time_s    diff_s
0     1    72.300           1   72.311132 -0.011132
1     2   147.704           2  147.707178 -0.003178
2     3    66.980           3   66.982599 -0.002599
3     4    65.544           4   65.545928 -0.001928
4     5    63.392           5   63.401974 -0.009974
5     6    62.476           6   62.475559  0.000441
6     7    64.048           7   64.048082 -0.000082
7     8    61.448           8   61.455120 -0.007120
8     9    61.188           9   61.189273 -0.001273
9    10    60.796          10   60.803161 -0.007161
10   11    61.464          11   61.471300 -0.007300
11   12    61.400          12   61.401227 -0.001227
12   13    61.764          13   61.769093 -0.005093
13   14   231.724          14  231.723847  0.000153
14   15    67.168          15   67.173039 -0.005039
15   16    63.708          16   63.715786 -0.007786
16   17    62.956          17   62.955445  0.000555
17   18    61.432          18   61.443194 -0.011194
18   19    61.180          19   61.179623  0.000377
19   20    67.256          20   67.260256 -0.004256
20   21    61.800          21   61.803228 -0.003228
21   22    63.652          22   63.653276 -0.001276
22   23    62.100          23   62.105580 -0.005580

In [11]:
old

,lap_number,start_s,end_s,lap_time_s,has_stop,has_gap,has_pit,is_out_lap,valid
0,1,61.447598,133.758730,72.311132,False,False,False,False,True
1,2,133.758730,281.465908,147.707178,True,False,False,False,False
2,3,281.465908,348.448507,66.982599,False,False,False,False,True
3,4,348.448507,413.994435,65.545928,False,False,False,False,True
4,5,413.994435,477.396409,63.401974,False,False,False,False,True
5,6,477.396409,539.871968,62.475559,False,False,False,False,True
6,7,539.871968,603.920050,64.048082,False,True,False,False,False
7,8,603.920050,665.375170,61.455120,False,False,False,False,True
8,9,665.375170,726.564443,61.189273,False,True,False,False,False
9,10,726.564443,787.367604,60.803161,False,True,False,False,False
10,11,787.367604,848.838904,61.471300,False,True,False,False,False
11,12,848.838904,910.240131,61.401227,False,False,False,False,True
12,13,910.240131,972.009224,61.769093,False,False,False,False,True
13,14,972.009224,1203.733071,231.723847,True,True,True,True,False
14,15,1203.733071,1270.906110,67.173039,False,False,False,False,True
15,16,1270.906110,1334.621896,63.715786,False,True,False,False,False
16,17,1334.621896,1397.577341,62.955445,False,False,False,False,True
17,18,1397.577341,1459.020535,61.443194,False,False,False,False,True
18,19,1459.020535,1520.200158,61.179623,False,False,False,False,True
19,20,1520.200158,1587.460414,67.260256,False,False,False,False,True
20,21,1587.460414,1649.263642,61.803228,False,True,False,False,False
21,22,1649.263642,1712.916918,63.653276,False,False,False,False,True
22,23,1712.916918,1775.022498,62.105580,False,False,False,False,True

In [12]:
gaps[gaps["lap"] == 13]

    lap     t_start       t_end  duration_s     s_start       s_end
28   13  932.768702  932.972702       0.204  336.602259  337.172448
29   13  944.664702  944.712702       0.048  489.425168  489.626273
30   13  959.664702  959.716702       0.052  692.559496  692.875990
31   13  968.864702  968.944702       0.080  780.226786  780.395555